AllCops:
  NewCops: enable
  Exclude:
    - db/migrate/**/*
    - db/schema.rb
    - config/**/*
    - script/**/*
    - bin/**/*
    - app/admin/**/*
    - app/channels/**/*
    - app/jobs/**/*
    - node_modules/**/*
    - Gemfile
    - Rakefile
    - config.ru
    - vendor/**/*

plugins: rubocop-rails

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/ClassLength:
  Enabled: false
