# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
AdminUser.create!(email: 'admin@example.com', password: 'passwordpassword', password_confirmation: 'passwordpassword') if Rails.env.development?
user = User.create!(email: 'user@example.com', password: 'passwordpassword', password_confirmation: 'passwordpassword') if Rails.env.development?
user_without_room = User.create!(email: 'user2@example.com', password: 'passwordpassword', password_confirmation: 'passwordpassword') if Rails.env.development?

Category.create!(name: 'Amplifiers', id: 1)
Category.create!(name: 'Headphones', id: 4)
Category.create!(name: 'Loudspeakers', id: 5)
Category.create!(name: 'Turntables', id: 7)
Category.create!(name: 'Digital', id: 8)

SubCategory.create!(name: 'Pre-Amplifiers', category_id: 1, id: 1)
SubCategory.create!(name: 'Phono Pre-Amplifiers', category_id: 1, id: 2)
SubCategory.create!(name: 'Integrated Amplifiers', category_id: 1, id: 3)
SubCategory.create!(name: 'Power Amplifiers', category_id: 1, id: 4)
SubCategory.create!(name: 'Headphone Amplifiers', category_id: 1, id: 5)
SubCategory.create!(name: 'In-Ear Headphones', category_id: 4, id: 6)
SubCategory.create!(name: 'On-Ear Headphones', category_id: 4, id: 7)
SubCategory.create!(name: 'Over-Ear Headphones', category_id: 4, id: 8)
SubCategory.create!(name: 'Noise Cancelling Headphones', category_id: 4, id: 9)
SubCategory.create!(name: 'Bookshelf Loudspeakers', category_id: 5, id: 10)
SubCategory.create!(name: 'Floorstanding Loudspeakers', category_id: 5, id: 11)
SubCategory.create!(name: 'Subwoofers', category_id: 5, id: 12)
SubCategory.create!(name: 'MM Cartridges', category_id: 7, id: 13)
SubCategory.create!(name: 'MC Cartridges', category_id: 7, id: 14)
SubCategory.create!(name: 'CD/SACD Players', category_id: 8, id: 15)
SubCategory.create!(name: 'DACs', category_id: 8, id: 16)
SubCategory.create!(name: 'Turntables', category_id: 7, id: 17)
SubCategory.create!(name: 'Tonearms', category_id: 7, id: 18)
SubCategory.create!(name: 'Streamer', category_id: 8, id: 19)
SubCategory.create!(name: 'Receiver', category_id: 1, id: 20)

Tag.create!(name: 'Solid State')
Tag.create!(name: 'Tube')

Manufacturer.create!(name: 'Audeze', id: 1)
Manufacturer.create!(name: 'Bluesound', id: 2)
Manufacturer.create!(name: 'Canton', id: 3)
Manufacturer.create!(name: 'Clearaudio', id: 4)
Manufacturer.create!(name: 'Denon', id: 5)
Manufacturer.create!(name: 'Feliks Audio', id: 6)
Manufacturer.create!(name: 'Fiio', id: 7)
Manufacturer.create!(name: 'Focal', id: 8)
Manufacturer.create!(name: 'Graham Slee', id: 9)
Manufacturer.create!(name: 'Musical Fidelity', id: 10)
Manufacturer.create!(name: 'Oppo', id: 11)
Manufacturer.create!(name: 'Shure', id: 12)
Manufacturer.create!(name: 'SMSL', id: 13)
Manufacturer.create!(name: 'Sony', id: 14)
Manufacturer.create!(name: 'Wharfedale', id: 15)
Manufacturer.create!(name: 'Willsenton', id: 16)
Manufacturer.create!(name: 'A & M Limited')
Manufacturer.create!(name: 'A.R. Electronics')
Manufacturer.create!(name: 'A.R.I.A. Advanced Research in Audio')
Manufacturer.create!(name: 'Aaron')
Manufacturer.create!(name: 'ABACUS electronics')
Manufacturer.create!(name: 'ABC Sound Lab')
Manufacturer.create!(name: 'Abyssound')
Manufacturer.create!(name: 'Acapella')
Manufacturer.create!(name: 'Accent Speaker Technology')
Manufacturer.create!(name: 'Accuphase')
Manufacturer.create!(name: 'ACCUSTIC ARTS')
Manufacturer.create!(name: 'Acoustic Energy')
Manufacturer.create!(name: 'Acoustic Reality ApS')
Manufacturer.create!(name: 'Acoustic Research')
Manufacturer.create!(name: 'Acoustic Signature')
Manufacturer.create!(name: 'Acoustic Solid')
Manufacturer.create!(name: 'Acoustic Zen')
Manufacturer.create!(name: 'Acoustic Signature')
Manufacturer.create!(name: 'ADAM Audio')
Manufacturer.create!(name: 'Adcom')
Manufacturer.create!(name: 'Advanced Sound')
Manufacturer.create!(name: 'Aerial Acoustics')
Manufacturer.create!(name: 'agile')
Manufacturer.create!(name: 'AKG')
Manufacturer.create!(name: 'AkustyK')
Manufacturer.create!(name: 'Albedo')
Manufacturer.create!(name: 'Alcons Audio')
#
Manufacturer.create!(name: 'Aletheia AV')
Manufacturer.create!(name: 'Aliante')
Manufacturer.create!(name: 'Alicja Unterschuetz acuhorn')
Manufacturer.create!(name: 'Almarro Products')
Manufacturer.create!(name: 'Alpha-Core, Inc.')
Manufacturer.create!(name: 'ALPHARD SOUND TECHNOLOGY ETP')
Manufacturer.create!(name: 'Alpine Electronics GmbH')
Manufacturer.create!(name: 'Alternate Audio')
Manufacturer.create!(name: 'Altmann Lautsprecher Systeme')
Manufacturer.create!(name: 'Alum Rock Technology')
Manufacturer.create!(name: 'AM Audio')
Manufacturer.create!(name: 'Amato Audio e.U.')
Manufacturer.create!(name: 'Ambiance Acoustics')
Manufacturer.create!(name: 'Ambience Speaker Systems')
Manufacturer.create!(name: 'American Acoustic Development LLC')
Manufacturer.create!(name: 'AMG (Analog Manufaktur Germany)')
Manufacturer.create!(name: 'Amiteque')
Manufacturer.create!(name: 'Amity Hifi, Anderson Electronic')
Manufacturer.create!(name: 'AMPARO')
Manufacturer.create!(name: 'Amphion Loudspeakers ltd')
Manufacturer.create!(name: 'Analysis Plus')
Manufacturer.create!(name: 'Anatek Audio')
Manufacturer.create!(name: 'Ancient Audio')
Manufacturer.create!(name: 'Ansae')
Manufacturer.create!(name: 'Anthem')
Manufacturer.create!(name: 'Anthony Gallo Acoustics')
Manufacturer.create!(name: 'Apature Products')
Manufacturer.create!(name: 'APERION AUDIO')
Manufacturer.create!(name: 'Apertura')
Manufacturer.create!(name: 'Apogee Sound')
Manufacturer.create!(name: 'Apollo')
Manufacturer.create!(name: 'April Music Inc.')
Manufacturer.create!(name: 'Aprilsound')
Manufacturer.create!(name: 'APS Spanily s.j.')
Manufacturer.create!(name: 'Arcam')
Manufacturer.create!(name: 'ARGENTUM')
Manufacturer.create!(name: 'Argos')
Manufacturer.create!(name: 'Aria')
Manufacturer.create!(name: 'Armour Home Electronics')
Manufacturer.create!(name: 'Art & Voice')
Manufacturer.create!(name: 'Art Audio Design')
Manufacturer.create!(name: 'Art Audio UK Ltd')
Manufacturer.create!(name: 'Art loudspeakers')
Manufacturer.create!(name: 'Art of Sound')
Manufacturer.create!(name: 'ARTECH')
Manufacturer.create!(name: 'ARTESANIA AUDIO')
Manufacturer.create!(name: 'Artisan Fidelity')
Manufacturer.create!(name: 'Artisan Silver Cables')
Manufacturer.create!(name: 'Artistic Audio Inc.')
Manufacturer.create!(name: 'ASCEND ACOUSTICS, INC.')
Manufacturer.create!(name: 'Ascendo GmbH')
Manufacturer.create!(name: 'ASPEN AMPLIFIERS Pty Ltd')
Manufacturer.create!(name: 'ASR Audiosysteme Friedrich Schäfer')
Manufacturer.create!(name: 'Astin Trew')
Manufacturer.create!(name: 'Atacama Audio')
Manufacturer.create!(name: 'ATC')
Manufacturer.create!(name: 'ATI')
Manufacturer.create!(name: 'Atlantic Technology')
Manufacturer.create!(name: 'Atlantis Power Quality Systems, Inc.')
Manufacturer.create!(name: 'Atlas (Scotland) Ltd.')
Manufacturer.create!(name: 'Atma-Sphere Music Systems Inc.')
Manufacturer.create!(name: 'Atoll Electronique')
Manufacturer.create!(name: 'ATRIUM Speakersystems')
Manufacturer.create!(name: 'Audes')
Manufacturer.create!(name: 'Audible Illusions')
Manufacturer.create!(name: 'Audience LLc')
Manufacturer.create!(name: 'Audimax-Hifi')
Manufacturer.create!(name: 'Audio Academy')
Manufacturer.create!(name: 'AUDIO AERO DESIGN')
Manufacturer.create!(name: 'AUDIO ANALOGUE S.r.l.')
Manufacturer.create!(name: 'Audio Artistry')
Manufacturer.create!(name: 'Audio Axiom')
Manufacturer.create!(name: 'Audio by Van Alstine, Inc.')
Manufacturer.create!(name: 'Audio Concepts, Inc.')
Manufacturer.create!(name: 'Audio Control')
Manufacturer.create!(name: 'audio equipment mauritz')
Manufacturer.create!(name: 'Audio Group UK Ltd')
Manufacturer.create!(name: 'Audio Magic')
Manufacturer.create!(name: 'AUDIO MEGA')
Manufacturer.create!(name: 'Audio Mirror')
Manufacturer.create!(name: 'Audio Note (UK) Ltd.')
Manufacturer.create!(name: 'Audio Odyssey')
Manufacturer.create!(name: 'Audio Physic GmbH')
Manufacturer.create!(name: 'Audio Plus Services')
Manufacturer.create!(name: 'Audio Pro AB')
Manufacturer.create!(name: 'Audio Products International Corp.')
Manufacturer.create!(name: 'Audio Research')
Manufacturer.create!(name: 'Audio Tekne')
Manufacturer.create!(name: 'Audio Workshop Raphael')
Manufacturer.create!(name: 'Audio-Technica')
Manufacturer.create!(name: 'Audioart')
Manufacturer.create!(name: 'Audioconnexion')
Manufacturer.create!(name: 'audiodata elektroakustik gmbh')
Manufacturer.create!(name: 'Audiofidem')
Manufacturer.create!(name: 'Audiomatus')
Manufacturer.create!(name: 'Audiomeca')
Manufacturer.create!(name: 'Audion')
Manufacturer.create!(name: 'AUDIONOVA')
Manufacturer.create!(name: 'Audioquest')
Manufacturer.create!(name: 'Audioroom')
Manufacturer.create!(name: 'AudioSound Laboratories')
Manufacturer.create!(name: 'AUDIOSTATIC HOLLAND')
Manufacturer.create!(name: 'AUDIOTHLON Sp.j.')
Manufacturer.create!(name: 'Audiovalve')
Manufacturer.create!(name: 'AuraSound, Inc.')
Manufacturer.create!(name: 'Aurus')
Manufacturer.create!(name: 'AV International Limited')
Manufacturer.create!(name: 'Avalon Acoustics')
Manufacturer.create!(name: 'Avalon Design')
Manufacturer.create!(name: 'Avance International A/S')
Manufacturer.create!(name: 'AVANCE VIDÉO')
Manufacturer.create!(name: 'Avantgarde Acoustic Lautsprechersysteme GmbH')
Manufacturer.create!(name: 'AVantGarde HIGH END AG')
Manufacturer.create!(name: 'AVID HiFi')
Manufacturer.create!(name: 'Avid')
Manufacturer.create!(name: 'AVM Next Generation Audio Technologies GmbH')
Manufacturer.create!(name: 'Axiom Audio')
Manufacturer.create!(name: 'Ayon Audio')
Manufacturer.create!(name: 'Ayre Acoustics')
Manufacturer.create!(name: 'B & K Components, Ltd.')
Manufacturer.create!(name: 'B.M.I.P./Billy Bags')
Manufacturer.create!(name: 'B&W Group Ltd')
Manufacturer.create!(name: 'Bag End Loudspeakers')
Manufacturer.create!(name: 'Balanced Audio Technology Inc.')
Manufacturer.create!(name: 'Baltlab')
Manufacturer.create!(name: 'Bang & Olufsen')
Manufacturer.create!(name: 'Basis Audio')
Manufacturer.create!(name: 'Bay Audio')
Manufacturer.create!(name: 'Bc Acoustique')
Manufacturer.create!(name: 'Beam-Echo Limited')
Manufacturer.create!(name: 'Beauhorn')
Manufacturer.create!(name: 'Bedini')
Manufacturer.create!(name: 'Bel Canto Design')
Manufacturer.create!(name: 'Benchmark Media Systems')
Manufacturer.create!(name: 'Bergmann Audio')
Manufacturer.create!(name: 'Better Cables LLC')
Manufacturer.create!(name: 'Beveridge Audio')
Manufacturer.create!(name: 'Beyerdynamic')
Manufacturer.create!(name: 'Birdland Audio')
Manufacturer.create!(name: 'Bladelius Design Group AB')
Manufacturer.create!(name: 'Blaupunkt GmbH')
Manufacturer.create!(name: 'BLOK Hi-Fi Stands')
Manufacturer.create!(name: 'Blue Amp, G. Becker')
Manufacturer.create!(name: 'Blue Circle Audio')
Manufacturer.create!(name: 'Blue Jeans Cable')
Manufacturer.create!(name: 'BMN')
Manufacturer.create!(name: 'Bogen Communications, Inc.')
Manufacturer.create!(name: 'Bohlender Graebener Corporation')
Manufacturer.create!(name: 'Bonsai Akustik')
Manufacturer.create!(name: 'Bose')
Manufacturer.create!(name: 'Boston Acoustics, Inc.')
Manufacturer.create!(name: 'Bottlehead Corp.')
Manufacturer.create!(name: 'Boulder Amplifiers, Inc.')
Manufacturer.create!(name: 'BOW Technologies ApS')
Manufacturer.create!(name: 'Brentworth Sound Lab')
Manufacturer.create!(name: 'Brick Wall Division')
Manufacturer.create!(name: 'Brinkmann Audio')
Manufacturer.create!(name: 'Brown Innovations')
Manufacturer.create!(name: 'Bryston')
Manufacturer.create!(name: 'Burmester Audiosysteme GmbH')
Manufacturer.create!(name: 'BWS Consulting')
Manufacturer.create!(name: 'Bybee Technologies')
Manufacturer.create!(name: 'C.E.C.')
Manufacturer.create!(name: 'CABASSE ACOUSTIC CENTER')
Manufacturer.create!(name: 'CABRE Hi-Fi')
Manufacturer.create!(name: 'CADENCE')
Manufacturer.create!(name: 'Calix Inc.')
Manufacturer.create!(name: 'Cambridge Audio')
Manufacturer.create!(name: 'Camelot Technology')
Manufacturer.create!(name: 'Campaign Audio Design')
Manufacturer.create!(name: 'Campfire Audio')
Manufacturer.create!(name: 'Caps & Coils')
Manufacturer.create!(name: 'Cardas Audio, Ltd.')
Manufacturer.create!(name: 'CARFRAE LOUDSPEAKERS')
Manufacturer.create!(name: 'Cary Audio')
Manufacturer.create!(name: 'Cayin')
Manufacturer.create!(name: 'CEC Europe // Braun & Quast')
Manufacturer.create!(name: 'CeEs!')
Manufacturer.create!(name: 'Celestion International Ltd.')
Manufacturer.create!(name: 'Centasound International Inc')
Manufacturer.create!(name: 'Ceratec Deutschland GmbH')
Manufacturer.create!(name: 'CERWIN-VEGA!, Inc.')
Manufacturer.create!(name: 'Channel Islands Audio')
Manufacturer.create!(name: 'CHARIO LOUDSPEAKERS')
Manufacturer.create!(name: 'CHISTO')
Manufacturer.create!(name: 'Chord Electronics Limited')
Manufacturer.create!(name: 'Cicable')
Manufacturer.create!(name: 'Clark Wire & Cable')
Manufacturer.create!(name: 'Classé Audio, Inc.')
Manufacturer.create!(name: 'Classe')
Manufacturer.create!(name: 'Clearlight Audio Vertrieb GmbH')
Manufacturer.create!(name: 'Cleer Audio')
Manufacturer.create!(name: 'Coincident Speaker Technology')
Manufacturer.create!(name: 'COMBAK CORPORATION')
Manufacturer.create!(name: 'Concept & Design audio')
Manufacturer.create!(name: 'Conrad-Johnson Design, Inc.')
Manufacturer.create!(name: 'Coph Nia Amplifiers')
Manufacturer.create!(name: 'Copland')
Manufacturer.create!(name: 'Cornu GmbH')
Manufacturer.create!(name: 'CPsound')
Manufacturer.create!(name: 'Creek Audio')
Manufacturer.create!(name: 'Crest Audio, Inc')
Manufacturer.create!(name: 'CRISS SYSTEMS')
Manufacturer.create!(name: 'Crusade-Audio')
Manufacturer.create!(name: 'Crystal Audio')
Manufacturer.create!(name: 'Crystal Cable BV')
Manufacturer.create!(name: 'Cubitel Audio Cable')
Manufacturer.create!(name: 'Cursio Audio Engineering')
Manufacturer.create!(name: 'Cygnus-Audio, Brückner&Melzer GbR')
Manufacturer.create!(name: 'Cyrus Audio')
Manufacturer.create!(name: 'D.H. Labs, Inc.')
Manufacturer.create!(name: 'Daburn electronics & cable corp.')
Manufacturer.create!(name: 'DALI')
Manufacturer.create!(name: 'Daluso')
Manufacturer.create!(name: 'Daniels Audio Corporation')
Manufacturer.create!(name: 'Dared Tube')
Manufacturer.create!(name: 'darTZeel Audio SA')
Manufacturer.create!(name: 'David Berning Company')
Manufacturer.create!(name: 'DaVinciAudio Labs GmbH')
Manufacturer.create!(name: 'DAVIS ACOUSTICS')
Manufacturer.create!(name: 'Dayens')
Manufacturer.create!(name: 'DCM Loudspeakers')
Manufacturer.create!(name: 'dCS Ltd')
Manufacturer.create!(name: 'Decware')
Manufacturer.create!(name: 'Definitive Technology')
Manufacturer.create!(name: 'deHavilland Electric Amplifier Co.')
Manufacturer.create!(name: 'Delta Studio s.c.')
Manufacturer.create!(name: 'Demeter')
Manufacturer.create!(name: 'Densen Audio Technologies')
Manufacturer.create!(name: 'DEQX Pty Limited')
Manufacturer.create!(name: 'Devialet')
Manufacturer.create!(name: 'DeVORE Fidelity')
Manufacturer.create!(name: 'DeZorel')
Manufacturer.create!(name: 'Diapason')
Manufacturer.create!(name: 'Diaural')
Manufacturer.create!(name: 'Digital Audio SA')
Manufacturer.create!(name: 'Direct Acoustics Incorporated')
Manufacturer.create!(name: 'Discovery cable')
Manufacturer.create!(name: 'Divatech')
Manufacturer.create!(name: 'Divergent Technologies Inc.,')
Manufacturer.create!(name: 'Divine Acoustics')
Manufacturer.create!(name: 'DLS Svenska AB')
Manufacturer.create!(name: 'DNM Design')
Manufacturer.create!(name: 'Docet digital hi fi')
Manufacturer.create!(name: 'DOCET-LECTOR')
Manufacturer.create!(name: 'Dodson Audio, Inc.')
Manufacturer.create!(name: 'Dr. Feickert Analogue')
Manufacturer.create!(name: 'DS Audio')
Manufacturer.create!(name: 'Dual')
Manufacturer.create!(name: 'Duevel')
Manufacturer.create!(name: 'Duntech Audio Australia Pty Ltd')
Manufacturer.create!(name: 'Dussun')
Manufacturer.create!(name: 'Dynaco Electronics')
Manufacturer.create!(name: 'Dynamic Solutions')
Manufacturer.create!(name: 'Dynaudio')
Manufacturer.create!(name: 'Dynavector System Ltd.')
Manufacturer.create!(name: 'E-Speakers.com LLC')
Manufacturer.create!(name: 'EAR Yoshino Ltd')
Manufacturer.create!(name: 'Earthquake Sound Corporation')
Manufacturer.create!(name: 'Eastern Electric Audio')
Manufacturer.create!(name: 'EAT (European Audio Team)')
Manufacturer.create!(name: 'eben BY RAIDHO')
Manufacturer.create!(name: 'Ecosse Reference Cables')
Manufacturer.create!(name: 'Ecotherm')
Manufacturer.create!(name: 'Edge Electronics')
Manufacturer.create!(name: 'EDY TON')
Manufacturer.create!(name: 'EGGLESTONWORKS')
Manufacturer.create!(name: 'Eichmann Technologies International')
Manufacturer.create!(name: 'Eighth Nerve')
Manufacturer.create!(name: 'EINSTEIN Audio Components')
Manufacturer.create!(name: 'EJ Jordan Ltd')
Manufacturer.create!(name: 'ELAC')
Manufacturer.create!(name: 'Elan')
Manufacturer.create!(name: 'Electra-Print Audio')
Manufacturer.create!(name: 'Electrocompaniet as')
Manufacturer.create!(name: 'Electron Luv')
Manufacturer.create!(name: 'Electronic Visionary Systems')
Manufacturer.create!(name: 'Elettromedia')
Manufacturer.create!(name: 'Elipson')
Manufacturer.create!(name: 'ELP Laser Turntable')
Manufacturer.create!(name: 'Eltax A/S')
Manufacturer.create!(name: 'Emil Scholz')
Manufacturer.create!(name: 'Eminence')
Manufacturer.create!(name: 'Eminent Audio')
Manufacturer.create!(name: 'Eminent Technology, Inc.')
Manufacturer.create!(name: 'Emission Lab')
Manufacturer.create!(name: 'Emotiva')
Manufacturer.create!(name: 'Emotive Audio Designs, Inc.')
Manufacturer.create!(name: 'Empirical Audio c/o Steve Nugent')
Manufacturer.create!(name: 'EMT (Elektro-Mess-Technik)')
Manufacturer.create!(name: 'Energy')
Manufacturer.create!(name: 'Ensemble AG')
Manufacturer.create!(name: 'Epos Ltd')
Manufacturer.create!(name: 'ER Audio')
Manufacturer.create!(name: 'ERYK S CONCEPT')
Manufacturer.create!(name: 'ESA')
Manufacturer.create!(name: 'Escient')
Manufacturer.create!(name: 'Esoteric')
Manufacturer.create!(name: 'Essential Sound Products, Inc.')
Manufacturer.create!(name: 'Ethera Loudspeaker Systems Ltd')
Manufacturer.create!(name: 'Etude Benelux BV')
Manufacturer.create!(name: 'Euro Acoustics')
Manufacturer.create!(name: 'EVENTUS Audio S.r.l.')
Manufacturer.create!(name: 'Eversolo')
Manufacturer.create!(name: 'Everything But The Box Ltd.')
Manufacturer.create!(name: 'Excentric')
Manufacturer.create!(name: 'Exposure Electronics')
Manufacturer.create!(name: 'Exposure')
Manufacturer.create!(name: 'Extreme Audio')
Manufacturer.create!(name: 'F.P.U.H. OSTOJA')
Manufacturer.create!(name: 'Fab Audio')
Manufacturer.create!(name: 'fadel Art')
Manufacturer.create!(name: 'Fanfare')
Manufacturer.create!(name: 'Fase')
Manufacturer.create!(name: 'Fern & Roby')
Manufacturer.create!(name: 'Fezz Audio')
Manufacturer.create!(name: 'Final Sound Solutions B.V.')
Manufacturer.create!(name: 'Finite Elemente')
Manufacturer.create!(name: 'Firestone Audio Co., Ltd.')
Manufacturer.create!(name: 'First Sound, Inc.')
Manufacturer.create!(name: 'Floating Systems')
Manufacturer.create!(name: 'Focus Audio')
Manufacturer.create!(name: 'Forsman AS(ltd)')
Manufacturer.create!(name: 'Fostex')
Manufacturer.create!(name: 'Fountek Electronics Co.,Ltd')
Manufacturer.create!(name: 'Frazier')
Manufacturer.create!(name: 'Frenzel Tube Amps')
Manufacturer.create!(name: 'FUJITSU TEN LIMITED')
Manufacturer.create!(name: 'Funk Firm')
Manufacturer.create!(name: 'FURUTECH CO.,LTD.')
Manufacturer.create!(name: 'Future Sound')
Manufacturer.create!(name: 'GamuT International A/S')
Manufacturer.create!(name: 'Garrard and Loricraft Audio')
Manufacturer.create!(name: 'Garrard')
Manufacturer.create!(name: 'Gemme Audio')
Manufacturer.create!(name: 'Genelec Oy')
Manufacturer.create!(name: 'Genesis Advanced Technologies')
Manufacturer.create!(name: 'Gepco International, Inc.')
Manufacturer.create!(name: 'German Physics')
Manufacturer.create!(name: 'Gershman Acoustics')
Manufacturer.create!(name: 'GigaWatt')
Manufacturer.create!(name: 'GLD')
Manufacturer.create!(name: 'Gold Sky Inc.')
Manufacturer.create!(name: 'Golden Sound')
Manufacturer.create!(name: 'GoldenEar Technology')
Manufacturer.create!(name: 'Goldmund')
Manufacturer.create!(name: 'Goldring')
Manufacturer.create!(name: 'Gotham AG Audio Cables')
Manufacturer.create!(name: 'GR Research Inc.')
Manufacturer.create!(name: 'Graaf s.r.l.')
Manufacturer.create!(name: 'Gradient Ltd')
Manufacturer.create!(name: 'Grado Labs')
Manufacturer.create!(name: 'Graham Engineering, inc.')
Manufacturer.create!(name: 'Granite Audio')
Manufacturer.create!(name: 'Green Mountain Audio')
Manufacturer.create!(name: 'Greybeard Audio')
Manufacturer.create!(name: 'GRONEBERG HiFi-Technik')
Manufacturer.create!(name: 'GRUENSCH Audiotechnik')
Manufacturer.create!(name: 'Gryphon')
Manufacturer.create!(name: 'Guangzhou Liwei Electronics Co., Ltd.')
Manufacturer.create!(name: 'gulang audio system')
Manufacturer.create!(name: 'GutWire Audio Cables')
Manufacturer.create!(name: 'Hafler')
Manufacturer.create!(name: 'Hagerman Technology LLC')
Manufacturer.create!(name: 'Halcro Audio')
Manufacturer.create!(name: 'Hans M. Strassner GmbH')
Manufacturer.create!(name: 'Hanss Acoustics')
Manufacturer.create!(name: 'Harbeth')
Manufacturer.create!(name: 'Harmonic Resolution Systems Inc.')
Manufacturer.create!(name: 'Harmonic Technology')
Manufacturer.create!(name: 'Harpia Acoustics')
Manufacturer.create!(name: 'Hawk Audio')
Manufacturer.create!(name: 'HB Cable Design')
Manufacturer.create!(name: 'HeadRoom')
Manufacturer.create!(name: 'Heco Audio-Produkte GmbH')
Manufacturer.create!(name: 'Hefei Xiangsheng Electronic Co. Ltd')
Manufacturer.create!(name: 'Hegel')
Manufacturer.create!(name: 'Hensler Elektronik')
Manufacturer.create!(name: 'HENZHEN SHANLING CO.,LTD.')
Manufacturer.create!(name: 'Hepta Design Audio')
Manufacturer.create!(name: 'Herron Audio')
Manufacturer.create!(name: 'Heybrook Hi-Fi')
Manufacturer.create!(name: 'HGP LAUTSPRECHER')
Manufacturer.create!(name: 'Hi End Audio Technology KORA')
Manufacturer.create!(name: 'Hi-End Racks')
Manufacturer.create!(name: 'Hi-Stands')
Manufacturer.create!(name: 'HiDiamond srl')
Manufacturer.create!(name: 'Hifiman')
Manufacturer.create!(name: 'High-Wire')
Manufacturer.create!(name: 'HighEndAudio, LLC')
Manufacturer.create!(name: 'HiVi, Inc.')
Manufacturer.create!(name: 'HL AUDIO ELECTRONIC CO.,LTD')
Manufacturer.create!(name: 'HNE Systems')
Manufacturer.create!(name: 'Holfi Audio International')
Manufacturer.create!(name: 'Hollywood Sound Labs')
Manufacturer.create!(name: 'Holo Audio')
Manufacturer.create!(name: 'Homegrown Audio Co.')
Manufacturer.create!(name: 'Hosa Technology, Inc.')
Manufacturer.create!(name: 'Hovland Company')
Manufacturer.create!(name: 'Hsu Research Inc.')
Manufacturer.create!(name: 'Huff Loudspeaker Co.')
Manufacturer.create!(name: 'Huygens Audio')
Manufacturer.create!(name: 'Hyperion Sound Design, Inc.')
Manufacturer.create!(name: 'I/K Audio')
Manufacturer.create!(name: 'ICHOS Schallwandler')
Manufacturer.create!(name: 'Icon Audio')
Manufacturer.create!(name: 'Icos')
Manufacturer.create!(name: 'IDEKTRON Unternehmens und Technologieberatung GmbH & Co.')
Manufacturer.create!(name: 'iharp Audio')
Manufacturer.create!(name: 'Immedia')
Manufacturer.create!(name: 'Induction Dynamics')
Manufacturer.create!(name: 'Inner Sound')
Manufacturer.create!(name: 'INKLANG')
Manufacturer.create!(name: 'Inovadis')
Manufacturer.create!(name: 'Isophon')
Manufacturer.create!(name: 'IXOS Limited')
Manufacturer.create!(name: 'J. Sikora')
Manufacturer.create!(name: 'J.A.Michell Engineering')
Manufacturer.create!(name: 'J.C.Verdier')
Manufacturer.create!(name: 'Jadis')
Manufacturer.create!(name: 'JAG ELECTRONICS')
Manufacturer.create!(name: 'James Monroe Wire and Cable Corporation')
Manufacturer.create!(name: 'Jamo International ApS')
Manufacturer.create!(name: 'JBL')
Manufacturer.create!(name: 'JC Audio')
Manufacturer.create!(name: 'JEAN MARIE REYNAUD')
Manufacturer.create!(name: 'Jeff Rowland Design Group')
Manufacturer.create!(name: 'Jena Labs')
Manufacturer.create!(name: 'Jenving Technology AB')
Manufacturer.create!(name: 'JH Sound')
Manufacturer.create!(name: 'JIB-Germany')
Manufacturer.create!(name: 'JJ Audio Zest / JJAZ')
Manufacturer.create!(name: 'JJ Electronic')
Manufacturer.create!(name: 'JL Audio')
Manufacturer.create!(name: 'JoLida Inc.')
Manufacturer.create!(name: 'Joseph Audio')
Manufacturer.create!(name: 'Joule Electra')
Manufacturer.create!(name: 'JPS Labs LLC')
Manufacturer.create!(name: 'JTL')
Manufacturer.create!(name: 'Jungson')
Manufacturer.create!(name: 'K+H Vertriebs- und Entwicklungsgesellschaft mbH')
Manufacturer.create!(name: 'Karan Acoustics')
Manufacturer.create!(name: 'KARLEV-AUDIO AG')
Manufacturer.create!(name: 'KCE Technology Corporation')
Manufacturer.create!(name: 'KEF')
Manufacturer.create!(name: 'Kimber Cable')
Manufacturer.create!(name: 'Kinetic Audio')
Manufacturer.create!(name: 'KIOM')
Manufacturer.create!(name: 'Kirksaeter')
Manufacturer.create!(name: 'Klang Manufaktur')
Manufacturer.create!(name: 'KLH Audio Systems')
Manufacturer.create!(name: 'Klipsch')
Manufacturer.create!(name: 'Klyne Audio Arts, Ltd.')
Manufacturer.create!(name: 'Knoll Systems')
Manufacturer.create!(name: 'Kondo Audio Note Japan')
Manufacturer.create!(name: 'Korato Audio Group')
Manufacturer.create!(name: 'Koss Corporation')
Manufacturer.create!(name: 'Krell Industries')
Manufacturer.create!(name: 'Krix Loudspeakers Pty Ltd')
Manufacturer.create!(name: 'Kronos Audio')
Manufacturer.create!(name: 'Kuzma')
Manufacturer.create!(name: 'L C Audio Technology ApS')
Manufacturer.create!(name: 'L. Bösendorfer Klavierfabrik GmbH')
Manufacturer.create!(name: 'Lab.gruppen AB')
Manufacturer.create!(name: 'Laboga')
Manufacturer.create!(name: 'Labyrinthos')
Manufacturer.create!(name: 'LAMM INDUSTRIES INC.')
Manufacturer.create!(name: 'Lansche Audio Systems')
Manufacturer.create!(name: 'Lavardin Technologies')
Manufacturer.create!(name: 'Legacy Audio')
Manufacturer.create!(name: 'Legend Audio')
Manufacturer.create!(name: 'Lehmann Audio')
Manufacturer.create!(name: 'Lenco')
Manufacturer.create!(name: 'Lightspeed Audio')
Manufacturer.create!(name: 'Linar Audio Inc')
Manufacturer.create!(name: 'Lindemann audiotechnik GmbH')
Manufacturer.create!(name: 'Line Magnetic')
Manufacturer.create!(name: 'Linear Audio Research')
Manufacturer.create!(name: 'LINK audio components')
Manufacturer.create!(name: 'Linn')
Manufacturer.create!(name: 'Lithos Acoustics')
Manufacturer.create!(name: 'Living Voice')
Manufacturer.create!(name: 'LOG AUDIO GMBH')
Manufacturer.create!(name: 'Lowther Loudspeaker Systems')
Manufacturer.create!(name: 'LR Acoustics GmbH')
Manufacturer.create!(name: 'LST Audio Lab')
Manufacturer.create!(name: 'Lua HiFi Manufaktur, Helmut Lua, Kaufmann')
Manufacturer.create!(name: 'LUBELL LABS INC.')
Manufacturer.create!(name: 'Lumen White')
Manufacturer.create!(name: 'Luminous Audio Technology')
Manufacturer.create!(name: 'Luxman HK Limited')
Manufacturer.create!(name: 'Luxman')
Manufacturer.create!(name: 'LuxurAudio')
Manufacturer.create!(name: 'Madral')
Manufacturer.create!(name: 'Magnan Audio Cables')
Manufacturer.create!(name: 'Magnat Audio Produkte GmbH')
Manufacturer.create!(name: 'MAGNEPAN')
Manufacturer.create!(name: 'Magnum Dynalab Ltd.')
Manufacturer.create!(name: 'mains', closed: true)
Manufacturer.create!(name: 'Maker Audio')
Manufacturer.create!(name: 'Malvalve')
Manufacturer.create!(name: 'Manger Products')
Manufacturer.create!(name: 'Manley Laboratories, Inc.')
Manufacturer.create!(name: 'Marantz')
Manufacturer.create!(name: 'Marchand Electronics Inc.')
Manufacturer.create!(name: 'Margules Audio')
Manufacturer.create!(name: 'Marigo Audio')
Manufacturer.create!(name: 'Mark Levinson')
Manufacturer.create!(name: 'Marsh Sound Design')
Manufacturer.create!(name: 'Martin Lautsprechersysteme')
Manufacturer.create!(name: 'MartinLogan')
Manufacturer.create!(name: 'Master & Dynamic')
Manufacturer.create!(name: 'MasterSource Audio')
Manufacturer.create!(name: 'Matthew James LLC')
Manufacturer.create!(name: 'Maudiox')
Manufacturer.create!(name: 'MAXXSONICS Europe GmbH')
Manufacturer.create!(name: 'MBL Akustikgeräte GmbH')
Manufacturer.create!(name: 'McIntosh')
Manufacturer.create!(name: 'ME Sound')
Manufacturer.create!(name: 'Meridian Audio')
Manufacturer.create!(name: 'Merlin Music Systems')
Manufacturer.create!(name: 'Metaxas')
Manufacturer.create!(name: 'Metronome technologie')
Manufacturer.create!(name: 'Meze Audio')
Manufacturer.create!(name: 'MFaudio')
Manufacturer.create!(name: 'Michael (Mick) Maloney')
Manufacturer.create!(name: 'Michell Engineering')
Manufacturer.create!(name: 'Miller & Kreisel Sound Corporation')
Manufacturer.create!(name: 'Minima Audio')
Manufacturer.create!(name: 'Mirage Loudspeakers')
Manufacturer.create!(name: 'Mirus Audio, LLC')
Manufacturer.create!(name: 'Mission')
Manufacturer.create!(name: 'MIT Cables')
Manufacturer.create!(name: 'MOGAMI')
Manufacturer.create!(name: 'Monarchy Audio')
Manufacturer.create!(name: 'Monitor Audio Limited')
Manufacturer.create!(name: 'Monolite Design & Technology')
Manufacturer.create!(name: 'Monolithic Sound')
Manufacturer.create!(name: 'Monrio')
Manufacturer.create!(name: 'Monster Cable Products, Inc.')
Manufacturer.create!(name: 'Moon by Simaudio')
Manufacturer.create!(name: 'Mordaunt-Short')
Manufacturer.create!(name: 'Morel')
Manufacturer.create!(name: 'Morgan Audio Systems')
Manufacturer.create!(name: 'MSB Technology Corporation')
Manufacturer.create!(name: 'Music Connection')
Manufacturer.create!(name: 'Music Hall')
Manufacturer.create!(name: 'Mutine')
Manufacturer.create!(name: 'Myst?re - Durob Audio BV')
Manufacturer.create!(name: 'Mytek Digital')
Manufacturer.create!(name: 'MZX, INC.')
Manufacturer.create!(name: 'N-Audio')
Manufacturer.create!(name: 'NAD Electronics')
Manufacturer.create!(name: 'Nagaoka')
Manufacturer.create!(name: 'Naim Audio')
Manufacturer.create!(name: 'NAT Audio')
Manufacturer.create!(name: 'NBS Audio Cables')
Manufacturer.create!(name: 'NCS HIFI Sopot s.c.')
Manufacturer.create!(name: 'Nearfield Acoustics')
Manufacturer.create!(name: 'Neat Acoustics Ltd.')
Manufacturer.create!(name: 'Neel Sp. z o.o.')
Manufacturer.create!(name: 'NEODIO')
Manufacturer.create!(name: 'Neutral Cable')
Manufacturer.create!(name: 'New Audio Frontiers')
Manufacturer.create!(name: 'Newform Research')
Manufacturer.create!(name: 'NEXTON')
Manufacturer.create!(name: 'NHT')
Manufacturer.create!(name: 'Niles Audio Corporation')
Manufacturer.create!(name: 'Nirvana')
Manufacturer.create!(name: 'Nitty Gritty')
Manufacturer.create!(name: 'Nordost Corporation')
Manufacturer.create!(name: 'nOrh')
Manufacturer.create!(name: 'North Star Design Srl')
Manufacturer.create!(name: 'NotePerfect LOUDSPEAKERS')
Manufacturer.create!(name: 'Nottingham Analogue')
Manufacturer.create!(name: 'Nova Audio, Inc.')
Manufacturer.create!(name: 'NSM AUDIO')
Manufacturer.create!(name: 'Nubert electronic GmbH')
Manufacturer.create!(name: 'Nuda Veritas s.c.')
Manufacturer.create!(name: 'NuForce, Inc')
Manufacturer.create!(name: 'O.L.S. Audiotechnology')
Manufacturer.create!(name: 'Ocellia')
Manufacturer.create!(name: 'OCTAVE Audio')
Manufacturer.create!(name: 'OEM Systems Company')
Manufacturer.create!(name: 'Ohm Acoustics Corp.')
Manufacturer.create!(name: 'Oldfield')
Manufacturer.create!(name: 'omtec hifi components, Manfred Baier')
Manufacturer.create!(name: 'Onkyo')
Manufacturer.create!(name: 'Oracle Audio')
Manufacturer.create!(name: 'Origin Live, Unit 5')
Manufacturer.create!(name: 'Ortofon A/S')
Manufacturer.create!(name: 'Osborn')
Manufacturer.create!(name: 'oscarsaudio')
Manufacturer.create!(name: 'Oswalds Mill Audio')
Manufacturer.create!(name: 'Outlaw Audio')
Manufacturer.create!(name: 'OWI Incorporated')
Manufacturer.create!(name: 'Palmer Audio')
Manufacturer.create!(name: 'Panamax')
Manufacturer.create!(name: 'Paradigm')
Manufacturer.create!(name: 'Paradox')
Manufacturer.create!(name: 'Parasound Products, Inc.')
Manufacturer.create!(name: 'Parasound')
Manufacturer.create!(name: 'Pass Laboratories')
Manufacturer.create!(name: 'Pass Labs')
Manufacturer.create!(name: 'PATHOS ACOUSTICS SRL')
Manufacturer.create!(name: 'Patos')
Manufacturer.create!(name: 'PBN Audio')
Manufacturer.create!(name: 'Peachtree Audio')
Manufacturer.create!(name: 'Peak Consult International')
Manufacturer.create!(name: 'Penaudio')
Manufacturer.create!(name: 'Perreaux')
Manufacturer.create!(name: 'Phase Technology')
Manufacturer.create!(name: 'Philip R. Clements')
Manufacturer.create!(name: 'Philips')
Manufacturer.create!(name: 'PHL audio')
Manufacturer.create!(name: 'Phonar Akustik')
Manufacturer.create!(name: 'PhonoGraph')
Manufacturer.create!(name: 'PHONOSOPHIE / I. Hansen Vertriebs GmbH')
Manufacturer.create!(name: 'PHY-HP Haut parleurs')
Manufacturer.create!(name: 'Pickering Audio')
Manufacturer.create!(name: 'Pied Piper')
Manufacturer.create!(name: 'PIEGA SA')
Manufacturer.create!(name: 'Pioneer')
Manufacturer.create!(name: 'Piyano Sound Industries')
Manufacturer.create!(name: 'PJ Audio')
Manufacturer.create!(name: 'Placette Audio')
Manufacturer.create!(name: 'Plasencia & Hijos')
Manufacturer.create!(name: 'Plateau')
Manufacturer.create!(name: 'PLINIUS AUDIO LIMITED')
Manufacturer.create!(name: 'Pluto Audio Products')
Manufacturer.create!(name: 'PMC Limited')
Manufacturer.create!(name: 'PMC Speakers')
Manufacturer.create!(name: 'Podspeakers A/S')
Manufacturer.create!(name: 'Polk Audio')
Manufacturer.create!(name: 'Polycrystal')
Manufacturer.create!(name: 'Portal Audio')
Manufacturer.create!(name: 'Poth Audio')
Manufacturer.create!(name: 'Power Audio Laboratories')
Manufacturer.create!(name: 'Power Electronic Industries')
Manufacturer.create!(name: 'Power Modules Inc.')
Manufacturer.create!(name: 'PrimaLuna')
Manufacturer.create!(name: 'Primare Systems')
Manufacturer.create!(name: 'Primare')
Manufacturer.create!(name: 'Pro - Mal')
Manufacturer.create!(name: 'Pro Tonsil Sp. z o.o.')
Manufacturer.create!(name: 'Pro-Ject')
Manufacturer.create!(name: 'PROA INDIVIDUAL POLSKA')
Manufacturer.create!(name: 'ProAc')
Manufacturer.create!(name: 'Progressive Audio')
Manufacturer.create!(name: 'PS Audio')
Manufacturer.create!(name: 'PSB Speakers International')
Manufacturer.create!(name: 'Pure Note')
Manufacturer.create!(name: 'Pure Silver Sound')
Manufacturer.create!(name: 'Purist Audio Designs')
Manufacturer.create!(name: 'QBA')
Manufacturer.create!(name: 'Quad Electroacoustics Ltd')
Manufacturer.create!(name: 'Quad')
Manufacturer.create!(name: 'quadral GmbH & Co. KG')
Manufacturer.create!(name: 'Quadraspire Limited')
Manufacturer.create!(name: 'Quantum Group, Inc.')
Manufacturer.create!(name: 'Quested')
Manufacturer.create!(name: 'Quicksilver Audio')
Manufacturer.create!(name: 'R Audio')
Manufacturer.create!(name: 'Radian Audio Engineering')
Manufacturer.create!(name: 'RADICON')
Manufacturer.create!(name: 'Radii Audio')
Manufacturer.create!(name: 'Rainbow Electronics')
Manufacturer.create!(name: 'Räke Hifi/Vertrieb GmbH')
Manufacturer.create!(name: 'Rapco International')
Manufacturer.create!(name: 'RBH Sound')
Manufacturer.create!(name: 'RCF Spa')
Manufacturer.create!(name: 'RCM Audio')
Manufacturer.create!(name: 'RCM sc.')
Manufacturer.create!(name: 'Red Rose Music')
Manufacturer.create!(name: 'REDGUM Audio Pty Ltd')
Manufacturer.create!(name: 'Redpoint Audio Design LLC')
Manufacturer.create!(name: 'Reed')
Manufacturer.create!(name: 'Reflection Audio Design')
Manufacturer.create!(name: 'Rega Research')
Manufacturer.create!(name: 'Reimer Speaker Systems')
Manufacturer.create!(name: 'REL Acoustics Limited')
Manufacturer.create!(name: 'Relco Audio')
Manufacturer.create!(name: 'REMMOS AUDIO')
Manufacturer.create!(name: 'Renaissance Audio')
Manufacturer.create!(name: 'Resolution Audio')
Manufacturer.create!(name: 'Restek AG')
Manufacturer.create!(name: 'Reußenzehn')
Manufacturer.create!(name: 'Revel')
Manufacturer.create!(name: 'Revelation Audio Labs, Inc.')
Manufacturer.create!(name: 'Revolution Acoustics, Ltd')
Manufacturer.create!(name: 'Revox')
Manufacturer.create!(name: 'RhF')
Manufacturer.create!(name: 'Rix Rax Inc.')
Manufacturer.create!(name: 'RL Acoustique')
Manufacturer.create!(name: 'RLS')
Manufacturer.create!(name: 'Robert Bastani')
Manufacturer.create!(name: 'Rocktron')
Manufacturer.create!(name: 'Rockustics, Inc.')
Manufacturer.create!(name: 'Rogue Audio')
Manufacturer.create!(name: 'Roksan Audio Limited')
Manufacturer.create!(name: 'Roksan')
Manufacturer.create!(name: 'Role Audio')
Manufacturer.create!(name: 'Rose Industries Ltd')
Manufacturer.create!(name: 'Rotel')
Manufacturer.create!(name: 'Rothwell Audio')
Manufacturer.create!(name: 'ROWEN')
Manufacturer.create!(name: 'RPG Diffusor Systems, Inc.')
Manufacturer.create!(name: 'RR Audio Laboratory')
Manufacturer.create!(name: 'Running Springs Audio')
Manufacturer.create!(name: 'Russound')
Manufacturer.create!(name: 'SAC Thailand')
Manufacturer.create!(name: 'Salamander Designs')
Manufacturer.create!(name: 'SAT (Swedish Analog Technologies)')
Manufacturer.create!(name: 'Scandyna')
Manufacturer.create!(name: 'Schiit')
Manufacturer.create!(name: 'Schrödinger Audio (Confield Technology Limited)')
Manufacturer.create!(name: 'Schroers & Schroers GmbH & Co. KG')
Manufacturer.create!(name: 'Sehring Audio Systeme GmbH')
Manufacturer.create!(name: 'SEKIGUCHI MACHINE SALES CO.,LTD')
Manufacturer.create!(name: 'Sennheiser')
Manufacturer.create!(name: 'Sequence Design')
Manufacturer.create!(name: 'Seventh Veil')
Manufacturer.create!(name: 'Shahinian Acoustics Ltd.')
Manufacturer.create!(name: 'SHAKTI INNOVATIONS')
Manufacturer.create!(name: 'Shanling')
Manufacturer.create!(name: 'SHARKWIRE Nederland')
Manufacturer.create!(name: 'Sherwood America')
Manufacturer.create!(name: 'Shindo Laboratory')
Manufacturer.create!(name: 'Shunyata Research Inc.')
Manufacturer.create!(name: 'Siegbert Tessendorf')
Manufacturer.create!(name: 'SIEMEL INDUSTRIE')
Manufacturer.create!(name: 'SIGN AUDIO Technology')
Manufacturer.create!(name: 'Signals-SuperFi, LLC')
Manufacturer.create!(name: 'Signature Technologies, Inc.')
Manufacturer.create!(name: 'Silbersand GmbH')
Manufacturer.create!(name: 'Silent Running Audio')
Manufacturer.create!(name: 'Siltech B.V.')
Manufacturer.create!(name: 'Silver Audio')
Manufacturer.create!(name: 'Silverline Audio')
Manufacturer.create!(name: 'Silversmith Audio')
Manufacturer.create!(name: 'Simaudio')
Manufacturer.create!(name: 'Simetel SpA')
Manufacturer.create!(name: 'Sintron Vertriebs GmbH')
Manufacturer.create!(name: 'Skorpion')
Manufacturer.create!(name: 'SME')
Manufacturer.create!(name: 'Snell Acoustics')
Manufacturer.create!(name: 'SOAIY DIGITAL TECHNOLOGY CO., LTD')
Manufacturer.create!(name: 'Softone, Inc.')
Manufacturer.create!(name: 'Solid Tech')
Manufacturer.create!(name: 'SOLIDCOREAUDIO')
Manufacturer.create!(name: 'Soliloqy')
Manufacturer.create!(name: 'SOMMER CABLE GmbH')
Manufacturer.create!(name: 'Sonance')
Manufacturer.create!(name: 'Song Audio')
Manufacturer.create!(name: 'Sonicweld')
Manufacturer.create!(name: 'Sonique')
Manufacturer.create!(name: 'Sonneteer Audiophile')
Manufacturer.create!(name: 'Sonodore Microphones')
Manufacturer.create!(name: 'Sonos')
Manufacturer.create!(name: 'Sonus Faber')
Manufacturer.create!(name: 'Sonus Oliva, Andrzej Witek')
Manufacturer.create!(name: 'Sonus Systems')
Manufacturer.create!(name: 'Sophia Electric')
Manufacturer.create!(name: 'SOTA')
Manufacturer.create!(name: 'Sound Advance')
Manufacturer.create!(name: 'SOUND ANCHORS INC')
Manufacturer.create!(name: 'Sound Art')
Manufacturer.create!(name: 'Sound Dynamics')
Manufacturer.create!(name: 'Sound Lab')
Manufacturer.create!(name: 'Sound Project')
Manufacturer.create!(name: 'Soundcare')
Manufacturer.create!(name: 'Sounds of Silence')
Manufacturer.create!(name: 'Soundsphere')
Manufacturer.create!(name: 'Soundstring Cable Technologies')
Manufacturer.create!(name: 'SoundTube')
Manufacturer.create!(name: 'Sovereign')
Manufacturer.create!(name: 'Speaker Art')
Manufacturer.create!(name: 'SpeakerCraft')
Manufacturer.create!(name: 'Speakerdirect-StudioLAB')
Manufacturer.create!(name: 'Spectral Audio')
Manufacturer.create!(name: 'Spectron')
Manufacturer.create!(name: 'SPENDOR AUDIO SYSTEMS LTD')
Manufacturer.create!(name: 'Sphinx Laboratories')
Manufacturer.create!(name: 'Spielberg Audio Labs')
Manufacturer.create!(name: 'Spiral Groove')
Manufacturer.create!(name: 'SPL')
Manufacturer.create!(name: 'Spread Spectrum Technologies Inc.')
Manufacturer.create!(name: 'SSC Akcept Audio')
Manufacturer.create!(name: 'Stage lll concepts')
Manufacturer.create!(name: 'Stan White Audio')
Manufacturer.create!(name: 'Stanalog Audio, Inc.')
Manufacturer.create!(name: 'Stanton Magnetics')
Manufacturer.create!(name: 'Status Acoustics')
Manufacturer.create!(name: 'Stax')
Manufacturer.create!(name: 'Stenholt Audio')
Manufacturer.create!(name: 'Stereolith')
Manufacturer.create!(name: 'Stillpoints LLC, Paul Wakeen')
Manufacturer.create!(name: 'Straight Wire')
Manufacturer.create!(name: 'STRUSS AMPLIFIERS Zdzislaw Hrynkiewicz-Struss')
Manufacturer.create!(name: 'STST')
Manufacturer.create!(name: 'Studio 16 Hertz')
Manufacturer.create!(name: 'STX SOUNDSTATION')
Manufacturer.create!(name: 'Sumiko')
Manufacturer.create!(name: 'SunCoast Audio')
Manufacturer.create!(name: 'Sundial')
Manufacturer.create!(name: 'Sunfire')
Manufacturer.create!(name: 'Symposium Acoustics')
Manufacturer.create!(name: 'Synergistic Rechearch')
Manufacturer.create!(name: 'Synthesis')
Manufacturer.create!(name: 'T + A elektroakustik GmbH & Co. KG')
Manufacturer.create!(name: 'T.Hartwig-ELektronik')
Manufacturer.create!(name: 'Tact Audio')
Manufacturer.create!(name: 'TAD')
Manufacturer.create!(name: 'TALCOMP PRODUCTION')
Manufacturer.create!(name: 'Talk Electronics')
Manufacturer.create!(name: 'Talon Loudspeakers')
Manufacturer.create!(name: 'Tangent Audio')
Manufacturer.create!(name: 'Tannoy Ltd.')
Manufacturer.create!(name: 'Tara Labs')
Manufacturer.create!(name: 'TEAC')
Manufacturer.create!(name: 'Technics')
Manufacturer.create!(name: 'Technomad')
Manufacturer.create!(name: 'Tektron')
Manufacturer.create!(name: 'Tenor Audio')
Manufacturer.create!(name: 'Teres Audio Inc.')
Manufacturer.create!(name: 'Terrazzo Art Fidelity')
Manufacturer.create!(name: 'Tetra Speakers Inc.')
Manufacturer.create!(name: 'The Bluenote s.r.l.')
Manufacturer.create!(name: 'The Chord Company Ltd')
Manufacturer.create!(name: 'THE HORN SHOPPE')
Manufacturer.create!(name: 'The Wright Sound Company')
Manufacturer.create!(name: 'Thesis Acoustique')
Manufacturer.create!(name: 'Theta Digital Corporation')
Manufacturer.create!(name: 'Thiel Audio')
Manufacturer.create!(name: 'Thomas Scherer Audio Engineering')
Manufacturer.create!(name: 'Thor Audio')
Manufacturer.create!(name: 'Thorens')
Manufacturer.create!(name: 'Threshold Audio, Inc.')
Manufacturer.create!(name: 'Thule Audio ApS')
Manufacturer.create!(name: 'TIDAL Audio GmbH')
Manufacturer.create!(name: 'Tivoli Audio, LLC.')
Manufacturer.create!(name: 'TMR Elektronik GmbH')
Manufacturer.create!(name: 'Toby Corporation of America')
Manufacturer.create!(name: 'Ton Art')
Manufacturer.create!(name: 'Topping')
Manufacturer.create!(name: 'TOTEM ACOUSTIC')
Manufacturer.create!(name: 'Townshend Audio')
Manufacturer.create!(name: 'Trafomatic Audio')
Manufacturer.create!(name: 'Transcendent Sound, Inc.')
Manufacturer.create!(name: 'Transcriptors Limited')
Manufacturer.create!(name: 'Translife GmbH')
Manufacturer.create!(name: 'Transmission Audio')
Manufacturer.create!(name: 'Transparent Cable')
Manufacturer.create!(name: 'Transrotor')
Manufacturer.create!(name: 'Tri Mai')
Manufacturer.create!(name: 'Triad Speakers, Inc.')
Manufacturer.create!(name: 'Triangle Art')
Manufacturer.create!(name: 'Triangle Industries')
Manufacturer.create!(name: 'Tributaries Cable')
Manufacturer.create!(name: 'Trichord Research Ltd')
Manufacturer.create!(name: 'TRIGON ELEKTRONIK GmbH')
Manufacturer.create!(name: 'Triphazer.com')
Manufacturer.create!(name: 'True Colours Industries')
Manufacturer.create!(name: 'Turner Audio')
Manufacturer.create!(name: 'Twisted Pair Designs')
Manufacturer.create!(name: 'Tymphany Corporation')
Manufacturer.create!(name: 'UK Distribution SRL')
Manufacturer.create!(name: 'Ulla Scheu')
Manufacturer.create!(name: 'Ultrasone')
Manufacturer.create!(name: 'Ultrasound')
Manufacturer.create!(name: 'Unison Research')
Manufacturer.create!(name: 'UNISOUND PRODUCTION INC.')
Manufacturer.create!(name: 'Usher Audio Technology')
Manufacturer.create!(name: 'V-MODA')
Manufacturer.create!(name: 'Vans Evers')
Manufacturer.create!(name: 'VARO TECHNOLOGY CO., LTD.')
Manufacturer.create!(name: 'VDN OTL Tube Technology / VDN Elektronika d.o.o.')
Manufacturer.create!(name: 'Vector Transworld Corporation')
Manufacturer.create!(name: 'Velodyne')
Manufacturer.create!(name: 'Velum Cables for Music')
Manufacturer.create!(name: 'Verity Audio Inc.')
Manufacturer.create!(name: 'Vertere Acoustics')
Manufacturer.create!(name: 'Vincent (V.G.) Electronics Co.,Ltd.')
Manufacturer.create!(name: 'Vincent Audio')
Manufacturer.create!(name: 'Vincent')
Manufacturer.create!(name: 'VISONIK HiFi')
Manufacturer.create!(name: 'Vistron Audio Equipment Co.,Ltd')
Manufacturer.create!(name: 'Von Gaylord Audio')
Manufacturer.create!(name: 'VPI Industries')
Manufacturer.create!(name: 'VTL')
Manufacturer.create!(name: 'Wadia Digital')
Manufacturer.create!(name: 'WARCO')
Manufacturer.create!(name: 'Warsztat Audio TROKS, Marcin Klich')
Manufacturer.create!(name: 'Warwick Acoustics')
Manufacturer.create!(name: 'Wasatch Cable Works')
Manufacturer.create!(name: 'Waterworks Acoustics')
Manufacturer.create!(name: 'WattGate')
Manufacturer.create!(name: 'WAVAC')
Manufacturer.create!(name: 'Wavelength Audio, ltd.')
Manufacturer.create!(name: 'WBE . AUDIOELEKTRONIK')
Manufacturer.create!(name: 'WBT-Distribution GmbH')
Manufacturer.create!(name: 'WEGG3')
Manufacturer.create!(name: 'Welborne Labs')
Manufacturer.create!(name: 'Well Tempered Lab')
Manufacturer.create!(name: 'Western Electric')
Manufacturer.create!(name: 'Westlake Audio - Manufacturing')
Manufacturer.create!(name: 'Whatmough')
Manufacturer.create!(name: 'Wilson Audio')
Manufacturer.create!(name: 'Wilson Benesch Ltd')
Manufacturer.create!(name: 'Wire World')
Manufacturer.create!(name: 'Wirth Tonmaschinenbau GmbH')
Manufacturer.create!(name: 'Wisdom Audio Corporation')
Manufacturer.create!(name: 'WLM - LOUDSPEAKERS')
Manufacturer.create!(name: 'Wolcott Audio')
Manufacturer.create!(name: 'WOOD TECHNOLOGY')
Manufacturer.create!(name: 'WWNet Bozena Furgol')
Manufacturer.create!(name: 'WYETECH LABS')
Manufacturer.create!(name: 'XAVIAN ELECTRONICS s.r.o.')
Manufacturer.create!(name: 'Xindak')
Manufacturer.create!(name: 'XLO electric')
Manufacturer.create!(name: 'Yamaha')
Manufacturer.create!(name: 'YG Acoustics')
Manufacturer.create!(name: 'Z-Systems Audio Engineering')
Manufacturer.create!(name: 'Zanden Audio Systems Ltd.')
Manufacturer.create!(name: 'Zingali')
Manufacturer.create!(name: 'ZMF Headphones')
Manufacturer.create!(name: 'ZPUE')
Manufacturer.create!(name: 'Zu Audio')

products = [
  # Audeze
  Product.create!(name: 'LCD-2C', manufacturer_id: 1, sub_category_ids: [8]),
  # Bluesound
  Product.create!(name: 'Node', manufacturer_id: 2, sub_category_ids: [19]),
  # Canton
  Product.create!(name: 'Karat 720.2', manufacturer_id: 3, sub_category_ids: [10], discontinued: true),
  # Clearaudio
  Product.create!(name: 'Concept', manufacturer_id: 4, sub_category_ids: [17]),
  Product.create!(name: 'Concept MC', manufacturer_id: 4, sub_category_ids: [14]),
  # Denon
  Product.create!(name: 'AH-D9200', manufacturer_id: 5, sub_category_ids: [8]),
  # Feliks Audio
  Product.create!(name: 'Elise', manufacturer_id: 6, sub_category_ids: [5]),
  # Fiio
  Product.create!(name: 'E10K', manufacturer_id: 7, sub_category_ids: [5, 16]),
  Product.create!(name: 'K3', manufacturer_id: 7, sub_category_ids: [5, 16]),
  # Focal
  Product.create!(name: 'Elear', manufacturer_id: 8, sub_category_ids: [8]),
  # Graham Slee
  Product.create!(name: 'Ultra Linear II', manufacturer_id: 9, sub_category_ids: [5]),
  Product.create!(name: 'Reflex C', manufacturer_id: 9, sub_category_ids: [2]),
  # Musical Fidelity
  Product.create!(name: 'M5Si', manufacturer_id: 10, sub_category_ids: [3]),
  # Oppo
  Product.create!(name: 'PM-3', manufacturer_id: 11, sub_category_ids: [8]),
  # Shure
  Product.create!(name: 'SE215-CL', manufacturer_id: 12, sub_category_ids: [6]),
  # SMSL
  Product.create!(name: 'SA-50', manufacturer_id: 13, sub_category_ids: [3]),
  # Sony
  Product.create!(name: 'MDR-EX450', manufacturer_id: 14, sub_category_ids: [6]),
  # Wharfedale
  Product.create!(name: 'Linton 85th', manufacturer_id: 15, sub_category_ids: [11]),
  # Willsenton
  Product.create!(name: 'R300', manufacturer_id: 16, sub_category_ids: [3])
]

products.each do |product|
  user.products << product
end

living_room = Room.create!(name: 'Living Room')
office = Room.create!(name: 'Office')

user.rooms << living_room
user.rooms << office
user.save

products.each do |product|
  user_without_room.products << product
end
user_without_room.save

living_room.products << products[1]
living_room.products << products[3]
living_room.products << products[4]
living_room.products << products[6]
living_room.products << products[11]
living_room.products << products[12]
living_room.products << products[17]
living_room.products << products[18]
living_room.save

office.products << products[2]
office.products << products[7]
office.products << products[15]
office.save

# Clearaudio
Product.create!(name: 'Concept Active', manufacturer_id: 4, sub_category_ids: [17])
Product.create!(name: 'Emotion SE', manufacturer_id: 4, sub_category_ids: [17])
Product.create!(name: 'Performance DC', manufacturer_id: 4, sub_category_ids: [17])
Product.create!(name: 'Ovation', manufacturer_id: 4, sub_category_ids: [17])
Product.create!(name: 'Reference Jubilee', manufacturer_id: 4, sub_category_ids: [17])
Product.create!(name: 'Innovation', manufacturer_id: 4, sub_category_ids: [17])
Product.create!(name: 'Innovation Basic', manufacturer_id: 4, sub_category_ids: [17])
Product.create!(name: 'Innovation Compact', manufacturer_id: 4, sub_category_ids: [17])
Product.create!(name: 'Master Innovation', manufacturer_id: 4, sub_category_ids: [17])
Product.create!(name: 'Statement', manufacturer_id: 4, sub_category_ids: [17])
Product.create!(name: 'Nano Phono v2', manufacturer_id: 4, sub_category_ids: [2])
Product.create!(name: 'Verify', manufacturer_id: 4, sub_category_ids: [18])
Product.create!(name: 'Clarify', manufacturer_id: 4, sub_category_ids: [18])
Product.create!(name: 'Satisfy Kardan', manufacturer_id: 4, sub_category_ids: [18])
Product.create!(name: 'Profiler', manufacturer_id: 4, sub_category_ids: [18])
Product.create!(name: 'Unify', manufacturer_id: 4, sub_category_ids: [18])
Product.create!(name: 'Tracer', manufacturer_id: 4, sub_category_ids: [18])
Product.create!(name: 'Magnify', manufacturer_id: 4, sub_category_ids: [18])
Product.create!(name: 'Universal', manufacturer_id: 4, sub_category_ids: [18])
Product.create!(name: 'TT5', manufacturer_id: 4, sub_category_ids: [18])
Product.create!(name: 'TT3', manufacturer_id: 4, sub_category_ids: [18])
Product.create!(name: 'TT2', manufacturer_id: 4, sub_category_ids: [18])
Product.create!(name: 'MM Concept v2', manufacturer_id: 4, sub_category_ids: [13])
Product.create!(name: 'MM Jubilee', manufacturer_id: 4, sub_category_ids: [13])
Product.create!(name: 'Concept MC', manufacturer_id: 4, sub_category_ids: [14])
Product.create!(name: 'Essence MC', manufacturer_id: 4, sub_category_ids: [14])

# Denon
Product.create!(name: 'AH-MM400', manufacturer_id: 5, sub_category_ids: [8], discontinued: true)
Product.create!(name: 'AH-D1000', manufacturer_id: 5, sub_category_ids: [8])
Product.create!(name: 'AH-D5200', manufacturer_id: 5, sub_category_ids: [8])
Product.create!(name: 'AH-D7200', manufacturer_id: 5, sub_category_ids: [8])

# Feliks Audio
Product.create!(name: 'Envy', manufacturer_id: 6, sub_category_ids: [5])
Product.create!(name: 'Euforia Anniversary', manufacturer_id: 6, sub_category_ids: [5])
Product.create!(name: 'Euforia Evo', manufacturer_id: 6, sub_category_ids: [5])
Product.create!(name: 'Echo 2', manufacturer_id: 6, sub_category_ids: [5])
Product.create!(name: 'Arioso 300B', manufacturer_id: 6, sub_category_ids: [3])

# Musical Fidelity
Product.create!(name: 'M3Si', manufacturer_id: 10, sub_category_ids: [3])
Product.create!(name: 'M6Si', manufacturer_id: 10, sub_category_ids: [3])

# Wharfedale
Product.create!(name: 'Denton 85th', manufacturer_id: 15, sub_category_ids: [10])
Product.create!(name: 'Dovedale', manufacturer_id: 15, sub_category_ids: [11])

# Willsenton
Product.create!(name: 'R8', manufacturer_id: 16, sub_category_ids: [3])
Product.create!(name: 'R800i', manufacturer_id: 16, sub_category_ids: [3])
