# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
AdminUser.create!(email: 'admin@example.com', password: 'passwordpassword', password_confirmation: 'passwordpassword') if Rails.env.development?
# file deepcode ignore HardcodedPassword: <please specify a reason of ignoring this>
user = User.create!(email: 'user@example.com', password: 'passwordpassword', password_confirmation: 'passwordpassword') if Rails.env.development?
user_without_setup = User.create!(email: 'user2@example.com', password: 'passwordpassword', password_confirmation: 'passwordpassword') if Rails.env.development?

Category.create!(name: 'Amplifiers', id: 1)
Category.create!(name: 'Headphones', id: 4)
Category.create!(name: 'Loudspeakers', id: 5)
Category.create!(name: 'Turntables', id: 7)
Category.create!(name: 'Digital', id: 8)

SubCategory.create!(name: 'Pre-Amplifiers', category_id: 1, id: 1)
SubCategory.create!(name: 'Phono Pre-Amplifiers', category_id: 1, id: 2)
SubCategory.create!(name: 'Integrated Amplifiers', category_id: 1, id: 3)
SubCategory.create!(name: 'Power Amplifiers', category_id: 1, id: 4)
SubCategory.create!(name: 'Headphone Amplifiers', category_id: 1, id: 5)
SubCategory.create!(name: 'In-Ear Headphones', category_id: 4, id: 6)
SubCategory.create!(name: 'On-Ear Headphones', category_id: 4, id: 7)
SubCategory.create!(name: 'Over-Ear Headphones', category_id: 4, id: 8)
SubCategory.create!(name: 'Noise Cancelling Headphones', category_id: 4, id: 9)
SubCategory.create!(name: 'Bookshelf Loudspeakers', category_id: 5, id: 10)
SubCategory.create!(name: 'Floorstanding Loudspeakers', category_id: 5, id: 11)
SubCategory.create!(name: 'Subwoofers', category_id: 5, id: 12)
SubCategory.create!(name: 'MM Cartridges', category_id: 7, id: 13)
SubCategory.create!(name: 'MC Cartridges', category_id: 7, id: 14)
SubCategory.create!(name: 'CD/SACD Players', category_id: 8, id: 15)
SubCategory.create!(name: 'DACs', category_id: 8, id: 16)
SubCategory.create!(name: 'Turntables', category_id: 7, id: 17)
SubCategory.create!(name: 'Tonearms', category_id: 7, id: 18)
SubCategory.create!(name: 'Streamers', category_id: 8, id: 19)
SubCategory.create!(name: 'Receivers', category_id: 1, id: 20)

Brand.create!(name: 'Audeze', id: 1)
Brand.create!(name: 'Bluesound', id: 2)
Brand.create!(name: 'Canton', id: 3)
Brand.create!(name: 'Clearaudio', id: 4)
Brand.create!(name: 'Denon', id: 5)
Brand.create!(name: 'Feliks Audio', id: 6)
Brand.create!(name: 'Fiio', id: 7)
Brand.create!(name: 'Focal', id: 8)
Brand.create!(name: 'Graham Slee', id: 9)
Brand.create!(name: 'Musical Fidelity', id: 10)
Brand.create!(name: 'Oppo', id: 11)
Brand.create!(name: 'Shure', id: 12)
Brand.create!(name: 'SMSL', id: 13)
Brand.create!(name: 'Sony', id: 14)
Brand.create!(name: 'Wharfedale', id: 15)
Brand.create!(name: 'Willsenton', id: 16)
Brand.create!(name: 'Sennheiser', id: 17)
Brand.create!(name: 'A & M Limited')
Brand.create!(name: 'A.R. Electronics')
Brand.create!(name: 'A.R.I.A. Advanced Research in Audio')
Brand.create!(name: 'Aaron')
Brand.create!(name: 'ABACUS electronics')
Brand.create!(name: 'ABC Sound Lab')
Brand.create!(name: 'Abyssound')
Brand.create!(name: 'Acapella')
Brand.create!(name: 'Accent Speaker Technology')
Brand.create!(name: 'Accuphase')
Brand.create!(name: 'ACCUSTIC ARTS')
Brand.create!(name: 'Acoustic Energy')
Brand.create!(name: 'Acoustic Reality ApS')
Brand.create!(name: 'Acoustic Research')
Brand.create!(name: 'Acoustic Signature')
Brand.create!(name: 'Acoustic Solid')
Brand.create!(name: 'Acoustic Zen')
Brand.create!(name: 'ADAM Audio')
Brand.create!(name: 'Adcom')
Brand.create!(name: 'Advanced Sound')
Brand.create!(name: 'Aerial Acoustics')
Brand.create!(name: 'agile')
Brand.create!(name: 'AKG')
Brand.create!(name: 'AkustyK')
Brand.create!(name: 'Albedo')
Brand.create!(name: 'Alcons Audio')
#
Brand.create!(name: 'Aletheia AV')
Brand.create!(name: 'Aliante')
Brand.create!(name: 'Alicja Unterschuetz acuhorn')
Brand.create!(name: 'Almarro Products')
Brand.create!(name: 'Alpha-Core, Inc.')
Brand.create!(name: 'ALPHARD SOUND TECHNOLOGY ETP')
Brand.create!(name: 'Alpine Electronics GmbH')
Brand.create!(name: 'Alternate Audio')
Brand.create!(name: 'Altmann Lautsprecher Systeme')
Brand.create!(name: 'Alum Rock Technology')
Brand.create!(name: 'AM Audio')
Brand.create!(name: 'Amato Audio e.U.')
Brand.create!(name: 'Ambiance Acoustics')
Brand.create!(name: 'Ambience Speaker Systems')
Brand.create!(name: 'American Acoustic Development LLC')
Brand.create!(name: 'AMG (Analog Manufaktur Germany)')
Brand.create!(name: 'Amiteque')
Brand.create!(name: 'Amity Hifi, Anderson Electronic')
Brand.create!(name: 'AMPARO')
Brand.create!(name: 'Amphion Loudspeakers ltd')
Brand.create!(name: 'Analysis Plus')
Brand.create!(name: 'Anatek Audio')
Brand.create!(name: 'Ancient Audio')
Brand.create!(name: 'Ansae')
Brand.create!(name: 'Anthem')
Brand.create!(name: 'Anthony Gallo Acoustics')
Brand.create!(name: 'Apature Products')
Brand.create!(name: 'APERION AUDIO')
Brand.create!(name: 'Apertura')
Brand.create!(name: 'Apogee Sound')
Brand.create!(name: 'Apollo')
Brand.create!(name: 'April Music Inc.')
Brand.create!(name: 'Aprilsound')
Brand.create!(name: 'APS Spanily s.j.')
Brand.create!(name: 'Arcam')
Brand.create!(name: 'ARGENTUM')
Brand.create!(name: 'Argos')
Brand.create!(name: 'Aria')
Brand.create!(name: 'Armour Home Electronics')
Brand.create!(name: 'Art & Voice')
Brand.create!(name: 'Art Audio Design')
Brand.create!(name: 'Art Audio UK Ltd')
Brand.create!(name: 'Art loudspeakers')
Brand.create!(name: 'Art of Sound')
Brand.create!(name: 'ARTECH')
Brand.create!(name: 'ARTESANIA AUDIO')
Brand.create!(name: 'Artisan Fidelity')
Brand.create!(name: 'Artisan Silver Cables')
Brand.create!(name: 'Artistic Audio Inc.')
Brand.create!(name: 'ASCEND ACOUSTICS, INC.')
Brand.create!(name: 'Ascendo GmbH')
Brand.create!(name: 'ASPEN AMPLIFIERS Pty Ltd')
Brand.create!(name: 'ASR Audiosysteme Friedrich Schäfer')
Brand.create!(name: 'Astin Trew')
Brand.create!(name: 'Atacama Audio')
Brand.create!(name: 'ATC')
Brand.create!(name: 'ATI')
Brand.create!(name: 'Atlantic Technology')
Brand.create!(name: 'Atlantis Power Quality Systems, Inc.')
Brand.create!(name: 'Atlas (Scotland) Ltd.')
Brand.create!(name: 'Atma-Sphere Music Systems Inc.')
Brand.create!(name: 'Atoll Electronique')
Brand.create!(name: 'ATRIUM Speakersystems')
Brand.create!(name: 'Audes')
Brand.create!(name: 'Audible Illusions')
Brand.create!(name: 'Audience LLc')
Brand.create!(name: 'Audimax-Hifi')
Brand.create!(name: 'Audio Academy')
Brand.create!(name: 'AUDIO AERO DESIGN')
Brand.create!(name: 'AUDIO ANALOGUE S.r.l.')
Brand.create!(name: 'Audio Artistry')
Brand.create!(name: 'Audio Axiom')
Brand.create!(name: 'Audio by Van Alstine, Inc.')
Brand.create!(name: 'Audio Concepts, Inc.')
Brand.create!(name: 'Audio Control')
Brand.create!(name: 'audio equipment mauritz')
Brand.create!(name: 'Audio Group UK Ltd')
Brand.create!(name: 'Audio Magic')
Brand.create!(name: 'AUDIO MEGA')
Brand.create!(name: 'Audio Mirror')
Brand.create!(name: 'Audio Note (UK) Ltd.')
Brand.create!(name: 'Audio Odyssey')
Brand.create!(name: 'Audio Physic GmbH')
Brand.create!(name: 'Audio Plus Services')
Brand.create!(name: 'Audio Pro AB')
Brand.create!(name: 'Audio Products International Corp.')
Brand.create!(name: 'Audio Research')
Brand.create!(name: 'Audio Tekne')
Brand.create!(name: 'Audio Workshop Raphael')
Brand.create!(name: 'Audio-Technica')
Brand.create!(name: 'Audioart')
Brand.create!(name: 'Audioconnexion')
Brand.create!(name: 'audiodata elektroakustik gmbh')
Brand.create!(name: 'Audiofidem')
Brand.create!(name: 'Audiomatus')
Brand.create!(name: 'Audiomeca')
Brand.create!(name: 'Audion')
Brand.create!(name: 'AUDIONOVA')
Brand.create!(name: 'Audioquest')
Brand.create!(name: 'Audioroom')
Brand.create!(name: 'AudioSound Laboratories')
Brand.create!(name: 'AUDIOSTATIC HOLLAND')
Brand.create!(name: 'AUDIOTHLON Sp.j.')
Brand.create!(name: 'Audiovalve')
Brand.create!(name: 'AuraSound, Inc.')
Brand.create!(name: 'Aurus')
Brand.create!(name: 'AV International Limited')
Brand.create!(name: 'Avalon Acoustics')
Brand.create!(name: 'Avalon Design')
Brand.create!(name: 'Avance International A/S')
Brand.create!(name: 'AVANCE VIDÉO')
Brand.create!(name: 'Avantgarde Acoustic Lautsprechersysteme GmbH')
Brand.create!(name: 'AVantGarde HIGH END AG')
Brand.create!(name: 'AVID HiFi')
Brand.create!(name: 'Avid')
Brand.create!(name: 'AVM Next Generation Audio Technologies GmbH')
Brand.create!(name: 'Axiom Audio')
Brand.create!(name: 'Ayon Audio')
Brand.create!(name: 'Ayre Acoustics')
Brand.create!(name: 'B & K Components, Ltd.')
Brand.create!(name: 'B.M.I.P./Billy Bags')
Brand.create!(name: 'B&W Group Ltd')
Brand.create!(name: 'Bag End Loudspeakers')
Brand.create!(name: 'Balanced Audio Technology Inc.')
Brand.create!(name: 'Baltlab')
Brand.create!(name: 'Bang & Olufsen')
Brand.create!(name: 'Basis Audio')
Brand.create!(name: 'Bay Audio')
Brand.create!(name: 'Bc Acoustique')
Brand.create!(name: 'Beam-Echo Limited')
Brand.create!(name: 'Beauhorn')
Brand.create!(name: 'Bedini')
Brand.create!(name: 'Bel Canto Design')
Brand.create!(name: 'Benchmark Media Systems')
Brand.create!(name: 'Bergmann Audio')
Brand.create!(name: 'Better Cables LLC')
Brand.create!(name: 'Beveridge Audio')
Brand.create!(name: 'Beyerdynamic')
Brand.create!(name: 'Birdland Audio')
Brand.create!(name: 'Bladelius Design Group AB')
Brand.create!(name: 'Blaupunkt GmbH')
Brand.create!(name: 'BLOK Hi-Fi Stands')
Brand.create!(name: 'Blue Amp, G. Becker')
Brand.create!(name: 'Blue Circle Audio')
Brand.create!(name: 'Blue Jeans Cable')
Brand.create!(name: 'BMN')
Brand.create!(name: 'Bogen Communications, Inc.')
Brand.create!(name: 'Bohlender Graebener Corporation')
Brand.create!(name: 'Bonsai Akustik')
Brand.create!(name: 'Bose')
Brand.create!(name: 'Boston Acoustics, Inc.')
Brand.create!(name: 'Bottlehead Corp.')
Brand.create!(name: 'Boulder Amplifiers, Inc.')
Brand.create!(name: 'BOW Technologies ApS')
Brand.create!(name: 'Brentworth Sound Lab')
Brand.create!(name: 'Brick Wall Division')
Brand.create!(name: 'Brinkmann Audio')
Brand.create!(name: 'Brown Innovations')
Brand.create!(name: 'Bryston')
Brand.create!(name: 'Burmester Audiosysteme GmbH')
Brand.create!(name: 'BWS Consulting')
Brand.create!(name: 'Bybee Technologies')
Brand.create!(name: 'C.E.C.')
Brand.create!(name: 'CABASSE ACOUSTIC CENTER')
Brand.create!(name: 'CABRE Hi-Fi')
Brand.create!(name: 'CADENCE')
Brand.create!(name: 'Calix Inc.')
Brand.create!(name: 'Cambridge Audio')
Brand.create!(name: 'Camelot Technology')
Brand.create!(name: 'Campaign Audio Design')
Brand.create!(name: 'Campfire Audio')
Brand.create!(name: 'Caps & Coils')
Brand.create!(name: 'Cardas Audio, Ltd.')
Brand.create!(name: 'CARFRAE LOUDSPEAKERS')
Brand.create!(name: 'Cary Audio')
Brand.create!(name: 'Cayin')
Brand.create!(name: 'CEC Europe // Braun & Quast')
Brand.create!(name: 'CeEs!')
Brand.create!(name: 'Celestion International Ltd.')
Brand.create!(name: 'Centasound International Inc')
Brand.create!(name: 'Ceratec Deutschland GmbH')
Brand.create!(name: 'CERWIN-VEGA!, Inc.')
Brand.create!(name: 'Channel Islands Audio')
Brand.create!(name: 'CHARIO LOUDSPEAKERS')
Brand.create!(name: 'CHISTO')
Brand.create!(name: 'Chord Electronics Limited')
Brand.create!(name: 'Cicable')
Brand.create!(name: 'Clark Wire & Cable')
Brand.create!(name: 'Classé Audio, Inc.')
Brand.create!(name: 'Classe')
Brand.create!(name: 'Clearlight Audio Vertrieb GmbH')
Brand.create!(name: 'Cleer Audio')
Brand.create!(name: 'Coincident Speaker Technology')
Brand.create!(name: 'COMBAK CORPORATION')
Brand.create!(name: 'Concept & Design audio')
Brand.create!(name: 'Conrad-Johnson Design, Inc.')
Brand.create!(name: 'Coph Nia Amplifiers')
Brand.create!(name: 'Copland')
Brand.create!(name: 'Cornu GmbH')
Brand.create!(name: 'CPsound')
Brand.create!(name: 'Creek Audio')
Brand.create!(name: 'Crest Audio, Inc')
Brand.create!(name: 'CRISS SYSTEMS')
Brand.create!(name: 'Crusade-Audio')
Brand.create!(name: 'Crystal Audio')
Brand.create!(name: 'Crystal Cable BV')
Brand.create!(name: 'Cubitel Audio Cable')
Brand.create!(name: 'Cursio Audio Engineering')
Brand.create!(name: 'Cygnus-Audio, Brückner&Melzer GbR')
Brand.create!(name: 'Cyrus Audio')
Brand.create!(name: 'D.H. Labs, Inc.')
Brand.create!(name: 'Daburn electronics & cable corp.')
Brand.create!(name: 'DALI')
Brand.create!(name: 'Daluso')
Brand.create!(name: 'Daniels Audio Corporation')
Brand.create!(name: 'Dared Tube')
Brand.create!(name: 'darTZeel Audio SA')
Brand.create!(name: 'David Berning Company')
Brand.create!(name: 'DaVinciAudio Labs GmbH')
Brand.create!(name: 'DAVIS ACOUSTICS')
Brand.create!(name: 'Dayens')
Brand.create!(name: 'DCM Loudspeakers')
Brand.create!(name: 'dCS Ltd')
Brand.create!(name: 'Decware')
Brand.create!(name: 'Definitive Technology')
Brand.create!(name: 'deHavilland Electric Amplifier Co.')
Brand.create!(name: 'Delta Studio s.c.')
Brand.create!(name: 'Demeter')
Brand.create!(name: 'Densen Audio Technologies')
Brand.create!(name: 'DEQX Pty Limited')
Brand.create!(name: 'Devialet')
Brand.create!(name: 'DeVORE Fidelity')
Brand.create!(name: 'DeZorel')
Brand.create!(name: 'Diapason')
Brand.create!(name: 'Diaural')
Brand.create!(name: 'Digital Audio SA')
Brand.create!(name: 'Direct Acoustics Incorporated')
Brand.create!(name: 'Discovery cable')
Brand.create!(name: 'Divatech')
Brand.create!(name: 'Divergent Technologies Inc.,')
Brand.create!(name: 'Divine Acoustics')
Brand.create!(name: 'DLS Svenska AB')
Brand.create!(name: 'DNM Design')
Brand.create!(name: 'Docet digital hi fi')
Brand.create!(name: 'DOCET-LECTOR')
Brand.create!(name: 'Dodson Audio, Inc.')
Brand.create!(name: 'Dr. Feickert Analogue')
Brand.create!(name: 'DS Audio')
Brand.create!(name: 'Dual')
Brand.create!(name: 'Duevel')
Brand.create!(name: 'Duntech Audio Australia Pty Ltd')
Brand.create!(name: 'Dussun')
Brand.create!(name: 'Dynaco Electronics')
Brand.create!(name: 'Dynamic Solutions')
Brand.create!(name: 'Dynaudio')
Brand.create!(name: 'Dynavector System Ltd.')
Brand.create!(name: 'E-Speakers.com LLC')
Brand.create!(name: 'EAR Yoshino Ltd')
Brand.create!(name: 'Earthquake Sound Corporation')
Brand.create!(name: 'Eastern Electric Audio')
Brand.create!(name: 'EAT (European Audio Team)')
Brand.create!(name: 'eben BY RAIDHO')
Brand.create!(name: 'Ecosse Reference Cables')
Brand.create!(name: 'Ecotherm')
Brand.create!(name: 'Edge Electronics')
Brand.create!(name: 'EDY TON')
Brand.create!(name: 'EGGLESTONWORKS')
Brand.create!(name: 'Eichmann Technologies International')
Brand.create!(name: 'Eighth Nerve')
Brand.create!(name: 'EINSTEIN Audio Components')
Brand.create!(name: 'EJ Jordan Ltd')
Brand.create!(name: 'ELAC')
Brand.create!(name: 'Elan')
Brand.create!(name: 'Electra-Print Audio')
Brand.create!(name: 'Electrocompaniet as')
Brand.create!(name: 'Electron Luv')
Brand.create!(name: 'Electronic Visionary Systems')
Brand.create!(name: 'Elettromedia')
Brand.create!(name: 'Elipson')
Brand.create!(name: 'ELP Laser Turntable')
Brand.create!(name: 'Eltax A/S')
Brand.create!(name: 'Emil Scholz')
Brand.create!(name: 'Eminence')
Brand.create!(name: 'Eminent Audio')
Brand.create!(name: 'Eminent Technology, Inc.')
Brand.create!(name: 'Emission Lab')
Brand.create!(name: 'Emotiva')
Brand.create!(name: 'Emotive Audio Designs, Inc.')
Brand.create!(name: 'Empirical Audio c/o Steve Nugent')
Brand.create!(name: 'EMT (Elektro-Mess-Technik)')
Brand.create!(name: 'Energy')
Brand.create!(name: 'Ensemble AG')
Brand.create!(name: 'Epos Ltd')
Brand.create!(name: 'ER Audio')
Brand.create!(name: 'ERYK S CONCEPT')
Brand.create!(name: 'ESA')
Brand.create!(name: 'Escient')
Brand.create!(name: 'Esoteric')
Brand.create!(name: 'Essential Sound Products, Inc.')
Brand.create!(name: 'Ethera Loudspeaker Systems Ltd')
Brand.create!(name: 'Etude Benelux BV')
Brand.create!(name: 'Euro Acoustics')
Brand.create!(name: 'EVENTUS Audio S.r.l.')
Brand.create!(name: 'Eversolo')
Brand.create!(name: 'Everything But The Box Ltd.')
Brand.create!(name: 'Excentric')
Brand.create!(name: 'Exposure Electronics')
Brand.create!(name: 'Exposure')
Brand.create!(name: 'Extreme Audio')
Brand.create!(name: 'F.P.U.H. OSTOJA')
Brand.create!(name: 'Fab Audio')
Brand.create!(name: 'fadel Art')
Brand.create!(name: 'Fanfare')
Brand.create!(name: 'Fase')
Brand.create!(name: 'Fern & Roby')
Brand.create!(name: 'Fezz Audio')
Brand.create!(name: 'Final Sound Solutions B.V.')
Brand.create!(name: 'Finite Elemente')
Brand.create!(name: 'Firestone Audio Co., Ltd.')
Brand.create!(name: 'First Sound, Inc.')
Brand.create!(name: 'Floating Systems')
Brand.create!(name: 'Focus Audio')
Brand.create!(name: 'Forsman AS(ltd)')
Brand.create!(name: 'Fostex')
Brand.create!(name: 'Fountek Electronics Co.,Ltd')
Brand.create!(name: 'Frazier')
Brand.create!(name: 'Frenzel Tube Amps')
Brand.create!(name: 'FUJITSU TEN LIMITED')
Brand.create!(name: 'Funk Firm')
Brand.create!(name: 'FURUTECH CO.,LTD.')
Brand.create!(name: 'Future Sound')
Brand.create!(name: 'GamuT International A/S')
Brand.create!(name: 'Garrard and Loricraft Audio')
Brand.create!(name: 'Garrard')
Brand.create!(name: 'Gemme Audio')
Brand.create!(name: 'Genelec Oy')
Brand.create!(name: 'Genesis Advanced Technologies')
Brand.create!(name: 'Gepco International, Inc.')
Brand.create!(name: 'German Physics')
Brand.create!(name: 'Gershman Acoustics')
Brand.create!(name: 'GigaWatt')
Brand.create!(name: 'GLD')
Brand.create!(name: 'Gold Sky Inc.')
Brand.create!(name: 'Golden Sound')
Brand.create!(name: 'GoldenEar Technology')
Brand.create!(name: 'Goldmund')
Brand.create!(name: 'Goldring')
Brand.create!(name: 'Gotham AG Audio Cables')
Brand.create!(name: 'GR Research Inc.')
Brand.create!(name: 'Graaf s.r.l.')
Brand.create!(name: 'Gradient Ltd')
Brand.create!(name: 'Grado Labs')
Brand.create!(name: 'Graham Engineering, inc.')
Brand.create!(name: 'Granite Audio')
Brand.create!(name: 'Green Mountain Audio')
Brand.create!(name: 'Greybeard Audio')
Brand.create!(name: 'GRONEBERG HiFi-Technik')
Brand.create!(name: 'GRUENSCH Audiotechnik')
Brand.create!(name: 'Gryphon')
Brand.create!(name: 'Guangzhou Liwei Electronics Co., Ltd.')
Brand.create!(name: 'gulang audio system')
Brand.create!(name: 'GutWire Audio Cables')
Brand.create!(name: 'Hafler')
Brand.create!(name: 'Hagerman Technology LLC')
Brand.create!(name: 'Halcro Audio')
Brand.create!(name: 'Hans M. Strassner GmbH')
Brand.create!(name: 'Hanss Acoustics')
Brand.create!(name: 'Harbeth')
Brand.create!(name: 'Harmonic Resolution Systems Inc.')
Brand.create!(name: 'Harmonic Technology')
Brand.create!(name: 'Harpia Acoustics')
Brand.create!(name: 'Hawk Audio')
Brand.create!(name: 'HB Cable Design')
Brand.create!(name: 'HeadRoom')
Brand.create!(name: 'Heco Audio-Produkte GmbH')
Brand.create!(name: 'Hefei Xiangsheng Electronic Co. Ltd')
Brand.create!(name: 'Hegel')
Brand.create!(name: 'Hensler Elektronik')
Brand.create!(name: 'HENZHEN SHANLING CO.,LTD.')
Brand.create!(name: 'Hepta Design Audio')
Brand.create!(name: 'Herron Audio')
Brand.create!(name: 'Heybrook Hi-Fi')
Brand.create!(name: 'HGP LAUTSPRECHER')
Brand.create!(name: 'Hi End Audio Technology KORA')
Brand.create!(name: 'Hi-End Racks')
Brand.create!(name: 'Hi-Stands')
Brand.create!(name: 'HiDiamond srl')
Brand.create!(name: 'Hifiman')
Brand.create!(name: 'High-Wire')
Brand.create!(name: 'HighEndAudio, LLC')
Brand.create!(name: 'HiVi, Inc.')
Brand.create!(name: 'HL AUDIO ELECTRONIC CO.,LTD')
Brand.create!(name: 'HNE Systems')
Brand.create!(name: 'Holfi Audio International')
Brand.create!(name: 'Hollywood Sound Labs')
Brand.create!(name: 'Holo Audio')
Brand.create!(name: 'Homegrown Audio Co.')
Brand.create!(name: 'Hosa Technology, Inc.')
Brand.create!(name: 'Hovland Company')
Brand.create!(name: 'Hsu Research Inc.')
Brand.create!(name: 'Huff Loudspeaker Co.')
Brand.create!(name: 'Huygens Audio')
Brand.create!(name: 'Hyperion Sound Design, Inc.')
Brand.create!(name: 'I/K Audio')
Brand.create!(name: 'ICHOS Schallwandler')
Brand.create!(name: 'Icon Audio')
Brand.create!(name: 'Icos')
Brand.create!(name: 'IDEKTRON Unternehmens und Technologieberatung GmbH & Co.')
Brand.create!(name: 'iharp Audio')
Brand.create!(name: 'Immedia')
Brand.create!(name: 'Induction Dynamics')
Brand.create!(name: 'Inner Sound')
Brand.create!(name: 'INKLANG')
Brand.create!(name: 'Inovadis')
Brand.create!(name: 'Isophon')
Brand.create!(name: 'IXOS Limited')
Brand.create!(name: 'J. Sikora')
Brand.create!(name: 'J.A.Michell Engineering')
Brand.create!(name: 'J.C.Verdier')
Brand.create!(name: 'Jadis')
Brand.create!(name: 'JAG ELECTRONICS')
Brand.create!(name: 'James Monroe Wire and Cable Corporation')
Brand.create!(name: 'Jamo International ApS')
Brand.create!(name: 'JBL')
Brand.create!(name: 'JC Audio')
Brand.create!(name: 'JEAN MARIE REYNAUD')
Brand.create!(name: 'Jeff Rowland Design Group')
Brand.create!(name: 'Jena Labs')
Brand.create!(name: 'Jenving Technology AB')
Brand.create!(name: 'JH Sound')
Brand.create!(name: 'JIB-Germany')
Brand.create!(name: 'JJ Audio Zest / JJAZ')
Brand.create!(name: 'JJ Electronic')
Brand.create!(name: 'JL Audio')
Brand.create!(name: 'JoLida Inc.')
Brand.create!(name: 'Joseph Audio')
Brand.create!(name: 'Joule Electra')
Brand.create!(name: 'JPS Labs LLC')
Brand.create!(name: 'JTL')
Brand.create!(name: 'Jungson')
Brand.create!(name: 'K+H Vertriebs- und Entwicklungsgesellschaft mbH')
Brand.create!(name: 'Karan Acoustics')
Brand.create!(name: 'KARLEV-AUDIO AG')
Brand.create!(name: 'KCE Technology Corporation')
Brand.create!(name: 'KEF')
Brand.create!(name: 'Kimber Cable')
Brand.create!(name: 'Kinetic Audio')
Brand.create!(name: 'KIOM')
Brand.create!(name: 'Kirksaeter')
Brand.create!(name: 'Klang Manufaktur')
Brand.create!(name: 'KLH Audio Systems')
Brand.create!(name: 'Klipsch')
Brand.create!(name: 'Klyne Audio Arts, Ltd.')
Brand.create!(name: 'Knoll Systems')
Brand.create!(name: 'Kondo Audio Note Japan')
Brand.create!(name: 'Korato Audio Group')
Brand.create!(name: 'Koss Corporation')
Brand.create!(name: 'Krell Industries')
Brand.create!(name: 'Krix Loudspeakers Pty Ltd')
Brand.create!(name: 'Kronos Audio')
Brand.create!(name: 'Kuzma')
Brand.create!(name: 'L C Audio Technology ApS')
Brand.create!(name: 'L. Bösendorfer Klavierfabrik GmbH')
Brand.create!(name: 'Lab.gruppen AB')
Brand.create!(name: 'Laboga')
Brand.create!(name: 'Labyrinthos')
Brand.create!(name: 'LAMM INDUSTRIES INC.')
Brand.create!(name: 'Lansche Audio Systems')
Brand.create!(name: 'Lavardin Technologies')
Brand.create!(name: 'Legacy Audio')
Brand.create!(name: 'Legend Audio')
Brand.create!(name: 'Lehmann Audio')
Brand.create!(name: 'Lenco')
Brand.create!(name: 'Lightspeed Audio')
Brand.create!(name: 'Linar Audio Inc')
Brand.create!(name: 'Lindemann audiotechnik GmbH')
Brand.create!(name: 'Line Magnetic')
Brand.create!(name: 'Linear Audio Research')
Brand.create!(name: 'LINK audio components')
Brand.create!(name: 'Linn')
Brand.create!(name: 'Lithos Acoustics')
Brand.create!(name: 'Living Voice')
Brand.create!(name: 'LOG AUDIO GMBH')
Brand.create!(name: 'Lowther Loudspeaker Systems')
Brand.create!(name: 'LR Acoustics GmbH')
Brand.create!(name: 'LST Audio Lab')
Brand.create!(name: 'Lua HiFi Manufaktur, Helmut Lua, Kaufmann')
Brand.create!(name: 'LUBELL LABS INC.')
Brand.create!(name: 'Lumen White')
Brand.create!(name: 'Luminous Audio Technology')
Brand.create!(name: 'Luxman HK Limited')
Brand.create!(name: 'Luxman')
Brand.create!(name: 'LuxurAudio')
Brand.create!(name: 'Madral')
Brand.create!(name: 'Magnan Audio Cables')
Brand.create!(name: 'Magnat Audio Produkte GmbH')
Brand.create!(name: 'MAGNEPAN')
Brand.create!(name: 'Magnum Dynalab Ltd.')
Brand.create!(name: 'mains', discontinued: true)
Brand.create!(name: 'Maker Audio')
Brand.create!(name: 'Malvalve')
Brand.create!(name: 'Manger Products')
Brand.create!(name: 'Manley Laboratories, Inc.')
Brand.create!(name: 'Marantz')
Brand.create!(name: 'Marchand Electronics Inc.')
Brand.create!(name: 'Margules Audio')
Brand.create!(name: 'Marigo Audio')
Brand.create!(name: 'Mark Levinson')
Brand.create!(name: 'Marsh Sound Design')
Brand.create!(name: 'Martin Lautsprechersysteme')
Brand.create!(name: 'MartinLogan')
Brand.create!(name: 'Master & Dynamic')
Brand.create!(name: 'MasterSource Audio')
Brand.create!(name: 'Matthew James LLC')
Brand.create!(name: 'Maudiox')
Brand.create!(name: 'MAXXSONICS Europe GmbH')
Brand.create!(name: 'MBL Akustikgeräte GmbH')
Brand.create!(name: 'McIntosh')
Brand.create!(name: 'ME Sound')
Brand.create!(name: 'Meridian Audio')
Brand.create!(name: 'Merlin Music Systems')
Brand.create!(name: 'Metaxas')
Brand.create!(name: 'Metronome technologie')
Brand.create!(name: 'Meze Audio')
Brand.create!(name: 'MFaudio')
Brand.create!(name: 'Michael (Mick) Maloney')
Brand.create!(name: 'Michell Engineering')
Brand.create!(name: 'Miller & Kreisel Sound Corporation')
Brand.create!(name: 'Minima Audio')
Brand.create!(name: 'Mirage Loudspeakers')
Brand.create!(name: 'Mirus Audio, LLC')
Brand.create!(name: 'Mission')
Brand.create!(name: 'MIT Cables')
Brand.create!(name: 'MOGAMI')
Brand.create!(name: 'Monarchy Audio')
Brand.create!(name: 'Monitor Audio Limited')
Brand.create!(name: 'Monolite Design & Technology')
Brand.create!(name: 'Monolithic Sound')
Brand.create!(name: 'Monrio')
Brand.create!(name: 'Monster Cable Products, Inc.')
Brand.create!(name: 'Moon by Simaudio')
Brand.create!(name: 'Mordaunt-Short')
Brand.create!(name: 'Morel')
Brand.create!(name: 'Morgan Audio Systems')
Brand.create!(name: 'MSB Technology Corporation')
Brand.create!(name: 'Music Connection')
Brand.create!(name: 'Music Hall')
Brand.create!(name: 'Mutine')
Brand.create!(name: 'Myst?re - Durob Audio BV')
Brand.create!(name: 'Mytek Digital')
Brand.create!(name: 'MZX, INC.')
Brand.create!(name: 'N-Audio')
Brand.create!(name: 'NAD Electronics')
Brand.create!(name: 'Nagaoka')
Brand.create!(name: 'Naim Audio')
Brand.create!(name: 'NAT Audio')
Brand.create!(name: 'NBS Audio Cables')
Brand.create!(name: 'NCS HIFI Sopot s.c.')
Brand.create!(name: 'Nearfield Acoustics')
Brand.create!(name: 'Neat Acoustics Ltd.')
Brand.create!(name: 'Neel Sp. z o.o.')
Brand.create!(name: 'NEODIO')
Brand.create!(name: 'Neutral Cable')
Brand.create!(name: 'New Audio Frontiers')
Brand.create!(name: 'Newform Research')
Brand.create!(name: 'NEXTON')
Brand.create!(name: 'NHT')
Brand.create!(name: 'Niles Audio Corporation')
Brand.create!(name: 'Nirvana')
Brand.create!(name: 'Nitty Gritty')
Brand.create!(name: 'Nordost Corporation')
Brand.create!(name: 'nOrh')
Brand.create!(name: 'North Star Design Srl')
Brand.create!(name: 'NotePerfect LOUDSPEAKERS')
Brand.create!(name: 'Nottingham Analogue')
Brand.create!(name: 'Nova Audio, Inc.')
Brand.create!(name: 'NSM AUDIO')
Brand.create!(name: 'Nubert electronic GmbH')
Brand.create!(name: 'Nuda Veritas s.c.')
Brand.create!(name: 'NuForce, Inc')
Brand.create!(name: 'O.L.S. Audiotechnology')
Brand.create!(name: 'Ocellia')
Brand.create!(name: 'OCTAVE Audio')
Brand.create!(name: 'OEM Systems Company')
Brand.create!(name: 'Ohm Acoustics Corp.')
Brand.create!(name: 'Oldfield')
Brand.create!(name: 'omtec hifi components, Manfred Baier')
Brand.create!(name: 'Onkyo')
Brand.create!(name: 'Oracle Audio')
Brand.create!(name: 'Origin Live, Unit 5')
Brand.create!(name: 'Ortofon A/S')
Brand.create!(name: 'Osborn')
Brand.create!(name: 'oscarsaudio')
Brand.create!(name: 'Oswalds Mill Audio')
Brand.create!(name: 'Outlaw Audio')
Brand.create!(name: 'OWI Incorporated')
Brand.create!(name: 'Palmer Audio')
Brand.create!(name: 'Panamax')
Brand.create!(name: 'Paradigm')
Brand.create!(name: 'Paradox')
Brand.create!(name: 'Parasound Products, Inc.')
Brand.create!(name: 'Parasound')
Brand.create!(name: 'Pass Laboratories')
Brand.create!(name: 'Pass Labs')
Brand.create!(name: 'PATHOS ACOUSTICS SRL')
Brand.create!(name: 'Patos')
Brand.create!(name: 'PBN Audio')
Brand.create!(name: 'Peachtree Audio')
Brand.create!(name: 'Peak Consult International')
Brand.create!(name: 'Penaudio')
Brand.create!(name: 'Perreaux')
Brand.create!(name: 'Phase Technology')
Brand.create!(name: 'Philip R. Clements')
Brand.create!(name: 'Philips')
Brand.create!(name: 'PHL audio')
Brand.create!(name: 'Phonar Akustik')
Brand.create!(name: 'PhonoGraph')
Brand.create!(name: 'PHONOSOPHIE / I. Hansen Vertriebs GmbH')
Brand.create!(name: 'PHY-HP Haut parleurs')
Brand.create!(name: 'Pickering Audio')
Brand.create!(name: 'Pied Piper')
Brand.create!(name: 'PIEGA SA')
Brand.create!(name: 'Pioneer')
Brand.create!(name: 'Piyano Sound Industries')
Brand.create!(name: 'PJ Audio')
Brand.create!(name: 'Placette Audio')
Brand.create!(name: 'Plasencia & Hijos')
Brand.create!(name: 'Plateau')
Brand.create!(name: 'PLINIUS AUDIO LIMITED')
Brand.create!(name: 'Pluto Audio Products')
Brand.create!(name: 'PMC Limited')
Brand.create!(name: 'PMC Speakers')
Brand.create!(name: 'Podspeakers A/S')
Brand.create!(name: 'Polk Audio')
Brand.create!(name: 'Polycrystal')
Brand.create!(name: 'Portal Audio')
Brand.create!(name: 'Poth Audio')
Brand.create!(name: 'Power Audio Laboratories')
Brand.create!(name: 'Power Electronic Industries')
Brand.create!(name: 'Power Modules Inc.')
Brand.create!(name: 'PrimaLuna')
Brand.create!(name: 'Primare Systems')
Brand.create!(name: 'Primare')
Brand.create!(name: 'Pro - Mal')
Brand.create!(name: 'Pro Tonsil Sp. z o.o.')
Brand.create!(name: 'Pro-Ject')
Brand.create!(name: 'PROA INDIVIDUAL POLSKA')
Brand.create!(name: 'ProAc')
Brand.create!(name: 'Progressive Audio')
Brand.create!(name: 'PS Audio')
Brand.create!(name: 'PSB Speakers International')
Brand.create!(name: 'Pure Note')
Brand.create!(name: 'Pure Silver Sound')
Brand.create!(name: 'Purist Audio Designs')
Brand.create!(name: 'QBA')
Brand.create!(name: 'Quad Electroacoustics Ltd')
Brand.create!(name: 'Quad')
Brand.create!(name: 'quadral GmbH & Co. KG')
Brand.create!(name: 'Quadraspire Limited')
Brand.create!(name: 'Quantum Group, Inc.')
Brand.create!(name: 'Quested')
Brand.create!(name: 'Quicksilver Audio')
Brand.create!(name: 'R Audio')
Brand.create!(name: 'Radian Audio Engineering')
Brand.create!(name: 'RADICON')
Brand.create!(name: 'Radii Audio')
Brand.create!(name: 'Rainbow Electronics')
Brand.create!(name: 'Räke Hifi/Vertrieb GmbH')
Brand.create!(name: 'Rapco International')
Brand.create!(name: 'RBH Sound')
Brand.create!(name: 'RCF Spa')
Brand.create!(name: 'RCM Audio')
Brand.create!(name: 'RCM sc.')
Brand.create!(name: 'Red Rose Music')
Brand.create!(name: 'REDGUM Audio Pty Ltd')
Brand.create!(name: 'Redpoint Audio Design LLC')
Brand.create!(name: 'Reed')
Brand.create!(name: 'Reflection Audio Design')
Brand.create!(name: 'Rega Research')
Brand.create!(name: 'Reimer Speaker Systems')
Brand.create!(name: 'REL Acoustics Limited')
Brand.create!(name: 'Relco Audio')
Brand.create!(name: 'REMMOS AUDIO')
Brand.create!(name: 'Renaissance Audio')
Brand.create!(name: 'Resolution Audio')
Brand.create!(name: 'Restek AG')
Brand.create!(name: 'Reußenzehn')
Brand.create!(name: 'Revel')
Brand.create!(name: 'Revelation Audio Labs, Inc.')
Brand.create!(name: 'Revolution Acoustics, Ltd')
Brand.create!(name: 'Revox')
Brand.create!(name: 'RhF')
Brand.create!(name: 'Rix Rax Inc.')
Brand.create!(name: 'RL Acoustique')
Brand.create!(name: 'RLS')
Brand.create!(name: 'Robert Bastani')
Brand.create!(name: 'Rocktron')
Brand.create!(name: 'Rockustics, Inc.')
Brand.create!(name: 'Rogue Audio')
Brand.create!(name: 'Roksan Audio Limited')
Brand.create!(name: 'Roksan')
Brand.create!(name: 'Role Audio')
Brand.create!(name: 'Rose Industries Ltd')
Brand.create!(name: 'Rotel')
Brand.create!(name: 'Rothwell Audio')
Brand.create!(name: 'ROWEN')
Brand.create!(name: 'RPG Diffusor Systems, Inc.')
Brand.create!(name: 'RR Audio Laboratory')
Brand.create!(name: 'Running Springs Audio')
Brand.create!(name: 'Russound')
Brand.create!(name: 'SAC Thailand')
Brand.create!(name: 'Salamander Designs')
Brand.create!(name: 'SAT (Swedish Analog Technologies)')
Brand.create!(name: 'Scandyna')
Brand.create!(name: 'Schiit')
Brand.create!(name: 'Schrödinger Audio (Confield Technology Limited)')
Brand.create!(name: 'Schroers & Schroers GmbH & Co. KG')
Brand.create!(name: 'Sehring Audio Systeme GmbH')
Brand.create!(name: 'SEKIGUCHI MACHINE SALES CO.,LTD')
Brand.create!(name: 'Sequence Design')
Brand.create!(name: 'Seventh Veil')
Brand.create!(name: 'Shahinian Acoustics Ltd.')
Brand.create!(name: 'SHAKTI INNOVATIONS')
Brand.create!(name: 'Shanling')
Brand.create!(name: 'SHARKWIRE Nederland')
Brand.create!(name: 'Sherwood America')
Brand.create!(name: 'Shindo Laboratory')
Brand.create!(name: 'Shunyata Research Inc.')
Brand.create!(name: 'Siegbert Tessendorf')
Brand.create!(name: 'SIEMEL INDUSTRIE')
Brand.create!(name: 'SIGN AUDIO Technology')
Brand.create!(name: 'Signals-SuperFi, LLC')
Brand.create!(name: 'Signature Technologies, Inc.')
Brand.create!(name: 'Silbersand GmbH')
Brand.create!(name: 'Silent Running Audio')
Brand.create!(name: 'Siltech B.V.')
Brand.create!(name: 'Silver Audio')
Brand.create!(name: 'Silverline Audio')
Brand.create!(name: 'Silversmith Audio')
Brand.create!(name: 'Simaudio')
Brand.create!(name: 'Simetel SpA')
Brand.create!(name: 'Sintron Vertriebs GmbH')
Brand.create!(name: 'Skorpion')
Brand.create!(name: 'SME')
Brand.create!(name: 'Snell Acoustics')
Brand.create!(name: 'SOAIY DIGITAL TECHNOLOGY CO., LTD')
Brand.create!(name: 'Softone, Inc.')
Brand.create!(name: 'Solid Tech')
Brand.create!(name: 'SOLIDCOREAUDIO')
Brand.create!(name: 'Soliloqy')
Brand.create!(name: 'SOMMER CABLE GmbH')
Brand.create!(name: 'Sonance')
Brand.create!(name: 'Song Audio')
Brand.create!(name: 'Sonicweld')
Brand.create!(name: 'Sonique')
Brand.create!(name: 'Sonneteer Audiophile')
Brand.create!(name: 'Sonodore Microphones')
Brand.create!(name: 'Sonos')
Brand.create!(name: 'Sonus Faber')
Brand.create!(name: 'Sonus Oliva, Andrzej Witek')
Brand.create!(name: 'Sonus Systems')
Brand.create!(name: 'Sophia Electric')
Brand.create!(name: 'SOTA')
Brand.create!(name: 'Sound Advance')
Brand.create!(name: 'SOUND ANCHORS INC')
Brand.create!(name: 'Sound Art')
Brand.create!(name: 'Sound Dynamics')
Brand.create!(name: 'Sound Lab')
Brand.create!(name: 'Sound Project')
Brand.create!(name: 'Soundcare')
Brand.create!(name: 'Sounds of Silence')
Brand.create!(name: 'Soundsphere')
Brand.create!(name: 'Soundstring Cable Technologies')
Brand.create!(name: 'SoundTube')
Brand.create!(name: 'Sovereign')
Brand.create!(name: 'Speaker Art')
Brand.create!(name: 'SpeakerCraft')
Brand.create!(name: 'Speakerdirect-StudioLAB')
Brand.create!(name: 'Spectral Audio')
Brand.create!(name: 'Spectron')
Brand.create!(name: 'SPENDOR AUDIO SYSTEMS LTD')
Brand.create!(name: 'Sphinx Laboratories')
Brand.create!(name: 'Spielberg Audio Labs')
Brand.create!(name: 'Spiral Groove')
Brand.create!(name: 'SPL')
Brand.create!(name: 'Spread Spectrum Technologies Inc.')
Brand.create!(name: 'SSC Akcept Audio')
Brand.create!(name: 'Stage lll concepts')
Brand.create!(name: 'Stan White Audio')
Brand.create!(name: 'Stanalog Audio, Inc.')
Brand.create!(name: 'Stanton Magnetics')
Brand.create!(name: 'Status Acoustics')
Brand.create!(name: 'Stax')
Brand.create!(name: 'Stenholt Audio')
Brand.create!(name: 'Stereolith')
Brand.create!(name: 'Stillpoints LLC, Paul Wakeen')
Brand.create!(name: 'Straight Wire')
Brand.create!(name: 'STRUSS AMPLIFIERS Zdzislaw Hrynkiewicz-Struss')
Brand.create!(name: 'STST')
Brand.create!(name: 'Studio 16 Hertz')
Brand.create!(name: 'STX SOUNDSTATION')
Brand.create!(name: 'Sumiko')
Brand.create!(name: 'SunCoast Audio')
Brand.create!(name: 'Sundial')
Brand.create!(name: 'Sunfire')
Brand.create!(name: 'Symposium Acoustics')
Brand.create!(name: 'Synergistic Rechearch')
Brand.create!(name: 'Synthesis')
Brand.create!(name: 'T + A elektroakustik GmbH & Co. KG')
Brand.create!(name: 'T.Hartwig-ELektronik')
Brand.create!(name: 'Tact Audio')
Brand.create!(name: 'TAD')
Brand.create!(name: 'TALCOMP PRODUCTION')
Brand.create!(name: 'Talk Electronics')
Brand.create!(name: 'Talon Loudspeakers')
Brand.create!(name: 'Tangent Audio')
Brand.create!(name: 'Tannoy Ltd.')
Brand.create!(name: 'Tara Labs')
Brand.create!(name: 'TEAC')
Brand.create!(name: 'Technics')
Brand.create!(name: 'Technomad')
Brand.create!(name: 'Tektron')
Brand.create!(name: 'Tenor Audio')
Brand.create!(name: 'Teres Audio Inc.')
Brand.create!(name: 'Terrazzo Art Fidelity')
Brand.create!(name: 'Tetra Speakers Inc.')
Brand.create!(name: 'The Bluenote s.r.l.')
Brand.create!(name: 'The Chord Company Ltd')
Brand.create!(name: 'THE HORN SHOPPE')
Brand.create!(name: 'The Wright Sound Company')
Brand.create!(name: 'Thesis Acoustique')
Brand.create!(name: 'Theta Digital Corporation')
Brand.create!(name: 'Thiel Audio')
Brand.create!(name: 'Thomas Scherer Audio Engineering')
Brand.create!(name: 'Thor Audio')
Brand.create!(name: 'Thorens')
Brand.create!(name: 'Threshold Audio, Inc.')
Brand.create!(name: 'Thule Audio ApS')
Brand.create!(name: 'TIDAL Audio GmbH')
Brand.create!(name: 'Tivoli Audio, LLC.')
Brand.create!(name: 'TMR Elektronik GmbH')
Brand.create!(name: 'Toby Corporation of America')
Brand.create!(name: 'Ton Art')
Brand.create!(name: 'Topping')
Brand.create!(name: 'TOTEM ACOUSTIC')
Brand.create!(name: 'Townshend Audio')
Brand.create!(name: 'Trafomatic Audio')
Brand.create!(name: 'Transcendent Sound, Inc.')
Brand.create!(name: 'Transcriptors Limited')
Brand.create!(name: 'Translife GmbH')
Brand.create!(name: 'Transmission Audio')
Brand.create!(name: 'Transparent Cable')
Brand.create!(name: 'Transrotor')
Brand.create!(name: 'Tri Mai')
Brand.create!(name: 'Triad Speakers, Inc.')
Brand.create!(name: 'Triangle Art')
Brand.create!(name: 'Triangle Industries')
Brand.create!(name: 'Tributaries Cable')
Brand.create!(name: 'Trichord Research Ltd')
Brand.create!(name: 'TRIGON ELEKTRONIK GmbH')
Brand.create!(name: 'Triphazer.com')
Brand.create!(name: 'True Colours Industries')
Brand.create!(name: 'Turner Audio')
Brand.create!(name: 'Twisted Pair Designs')
Brand.create!(name: 'Tymphany Corporation')
Brand.create!(name: 'UK Distribution SRL')
Brand.create!(name: 'Ulla Scheu')
Brand.create!(name: 'Ultrasone')
Brand.create!(name: 'Ultrasound')
Brand.create!(name: 'Unison Research')
Brand.create!(name: 'UNISOUND PRODUCTION INC.')
Brand.create!(name: 'Usher Audio Technology')
Brand.create!(name: 'V-MODA')
Brand.create!(name: 'Vans Evers')
Brand.create!(name: 'VARO TECHNOLOGY CO., LTD.')
Brand.create!(name: 'VDN OTL Tube Technology / VDN Elektronika d.o.o.')
Brand.create!(name: 'Vector Transworld Corporation')
Brand.create!(name: 'Velodyne')
Brand.create!(name: 'Velum Cables for Music')
Brand.create!(name: 'Verity Audio Inc.')
Brand.create!(name: 'Vertere Acoustics')
Brand.create!(name: 'Vincent (V.G.) Electronics Co.,Ltd.')
Brand.create!(name: 'Vincent Audio')
Brand.create!(name: 'Vincent')
Brand.create!(name: 'VISONIK HiFi')
Brand.create!(name: 'Vistron Audio Equipment Co.,Ltd')
Brand.create!(name: 'Von Gaylord Audio')
Brand.create!(name: 'VPI Industries')
Brand.create!(name: 'VTL')
Brand.create!(name: 'Wadia Digital')
Brand.create!(name: 'WARCO')
Brand.create!(name: 'Warsztat Audio TROKS, Marcin Klich')
Brand.create!(name: 'Warwick Acoustics')
Brand.create!(name: 'Wasatch Cable Works')
Brand.create!(name: 'Waterworks Acoustics')
Brand.create!(name: 'WattGate')
Brand.create!(name: 'WAVAC')
Brand.create!(name: 'Wavelength Audio, ltd.')
Brand.create!(name: 'WBE . AUDIOELEKTRONIK')
Brand.create!(name: 'WBT-Distribution GmbH')
Brand.create!(name: 'WEGG3')
Brand.create!(name: 'Welborne Labs')
Brand.create!(name: 'Well Tempered Lab')
Brand.create!(name: 'Western Electric')
Brand.create!(name: 'Westlake Audio - Manufacturing')
Brand.create!(name: 'Whatmough')
Brand.create!(name: 'Wilson Audio')
Brand.create!(name: 'Wilson Benesch Ltd')
Brand.create!(name: 'Wire World')
Brand.create!(name: 'Wirth Tonmaschinenbau GmbH')
Brand.create!(name: 'Wisdom Audio Corporation')
Brand.create!(name: 'WLM - LOUDSPEAKERS')
Brand.create!(name: 'Wolcott Audio')
Brand.create!(name: 'WOOD TECHNOLOGY')
Brand.create!(name: 'WWNet Bozena Furgol')
Brand.create!(name: 'WYETECH LABS')
Brand.create!(name: 'XAVIAN ELECTRONICS s.r.o.')
Brand.create!(name: 'Xindak')
Brand.create!(name: 'XLO electric')
Brand.create!(name: 'Yamaha')
Brand.create!(name: 'YG Acoustics')
Brand.create!(name: 'Z-Systems Audio Engineering')
Brand.create!(name: 'Zanden Audio Systems Ltd.')
Brand.create!(name: 'Zingali')
Brand.create!(name: 'ZMF Headphones')
Brand.create!(name: 'ZPUE')
Brand.create!(name: 'Zu Audio')

products = [
  # Audeze
  Product.create!(name: 'LCD-2C', brand_id: 1, sub_category_ids: [8]),
  # Bluesound
  Product.create!(name: 'Node', brand_id: 2, sub_category_ids: [19]),
  # Canton
  Product.create!(name: 'Karat 720.2', brand_id: 3, sub_category_ids: [10], discontinued: true),
  # Clearaudio
  Product.create!(name: 'Concept', brand_id: 4, sub_category_ids: [17]),
  Product.create!(name: 'Concept MC', brand_id: 4, sub_category_ids: [14]),
  # Denon
  Product.create!(name: 'AH-D9200', brand_id: 5, sub_category_ids: [8]),
  # Feliks Audio
  Product.create!(name: 'Elise', brand_id: 6, sub_category_ids: [5]),
  # Fiio
  Product.create!(name: 'E10K', brand_id: 7, sub_category_ids: [5, 16]),
  Product.create!(name: 'K3', brand_id: 7, sub_category_ids: [5, 16]),
  # Focal
  Product.create!(name: 'Elear', brand_id: 8, sub_category_ids: [8]),
  # Graham Slee
  Product.create!(name: 'Ultra Linear II', brand_id: 9, sub_category_ids: [5]),
  Product.create!(name: 'Reflex C', brand_id: 9, sub_category_ids: [2]),
  # Musical Fidelity
  Product.create!(name: 'M5Si', brand_id: 10, sub_category_ids: [3]),
  # Oppo
  Product.create!(name: 'PM-3', brand_id: 11, sub_category_ids: [8]),
  # Sennheiser
  Product.create!(name: 'HD 650', brand_id: 17, sub_category_ids: [8]),
  # Shure
  Product.create!(name: 'SE215-CL', brand_id: 12, sub_category_ids: [6]),
  # SMSL
  Product.create!(name: 'SA-50', brand_id: 13, sub_category_ids: [3]),
  # Sony
  Product.create!(name: 'MDR-EX450', brand_id: 14, sub_category_ids: [6]),
  # Wharfedale
  Product.create!(name: 'Linton 85th', brand_id: 15, sub_category_ids: [11]),
  # Willsenton
  Product.create!(name: 'R300', brand_id: 16, sub_category_ids: [3])
]

products.each do |product|
  user.products << product
end

living_room = Setup.create!(name: 'Living Room')
office = Setup.create!(name: 'Office')

user.setups << living_room
user.setups << office
user.save

products.each do |product|
  user_without_setup.products << product
end
user_without_setup.save

living_room.products << products[1]
living_room.products << products[3]
living_room.products << products[4]
living_room.products << products[6]
living_room.products << products[11]
living_room.products << products[12]
living_room.products << products[17]
living_room.products << products[18]
living_room.save

office.products << products[2]
office.products << products[7]
office.products << products[15]
office.save

# Clearaudio
Product.create!(name: 'Concept Active', brand_id: 4, sub_category_ids: [17])
Product.create!(name: 'Emotion SE', brand_id: 4, sub_category_ids: [17])
Product.create!(name: 'Performance DC', brand_id: 4, sub_category_ids: [17])
Product.create!(name: 'Ovation', brand_id: 4, sub_category_ids: [17])
Product.create!(name: 'Reference Jubilee', brand_id: 4, sub_category_ids: [17])
Product.create!(name: 'Innovation', brand_id: 4, sub_category_ids: [17])
Product.create!(name: 'Innovation Basic', brand_id: 4, sub_category_ids: [17])
Product.create!(name: 'Innovation Compact', brand_id: 4, sub_category_ids: [17])
Product.create!(name: 'Master Innovation', brand_id: 4, sub_category_ids: [17])
Product.create!(name: 'Statement', brand_id: 4, sub_category_ids: [17])
Product.create!(name: 'Nano Phono v2', brand_id: 4, sub_category_ids: [2])
Product.create!(name: 'Verify', brand_id: 4, sub_category_ids: [18])
Product.create!(name: 'Clarify', brand_id: 4, sub_category_ids: [18])
Product.create!(name: 'Satisfy Kardan', brand_id: 4, sub_category_ids: [18])
Product.create!(name: 'Profiler', brand_id: 4, sub_category_ids: [18])
Product.create!(name: 'Unify', brand_id: 4, sub_category_ids: [18])
Product.create!(name: 'Tracer', brand_id: 4, sub_category_ids: [18])
Product.create!(name: 'Magnify', brand_id: 4, sub_category_ids: [18])
Product.create!(name: 'Universal', brand_id: 4, sub_category_ids: [18])
Product.create!(name: 'TT5', brand_id: 4, sub_category_ids: [18])
Product.create!(name: 'TT3', brand_id: 4, sub_category_ids: [18])
Product.create!(name: 'TT2', brand_id: 4, sub_category_ids: [18])
Product.create!(name: 'MM Concept v2', brand_id: 4, sub_category_ids: [13])
Product.create!(name: 'MM Jubilee', brand_id: 4, sub_category_ids: [13])
Product.create!(name: 'Essence MC', brand_id: 4, sub_category_ids: [14])

# Denon
Product.create!(name: 'AH-MM400', brand_id: 5, sub_category_ids: [8], discontinued: true)
Product.create!(name: 'AH-D1000', brand_id: 5, sub_category_ids: [8])
Product.create!(name: 'AH-D5200', brand_id: 5, sub_category_ids: [8])
Product.create!(name: 'AH-D7200', brand_id: 5, sub_category_ids: [8])

# Feliks Audio
Product.create!(name: 'Envy', brand_id: 6, sub_category_ids: [5])
Product.create!(name: 'Euforia Anniversary', brand_id: 6, sub_category_ids: [5])
Product.create!(name: 'Euforia Evo', brand_id: 6, sub_category_ids: [5])
Product.create!(name: 'Echo 2', brand_id: 6, sub_category_ids: [5])
Product.create!(name: 'Arioso 300B', brand_id: 6, sub_category_ids: [3])

# Musical Fidelity
Product.create!(name: 'M3Si', brand_id: 10, sub_category_ids: [3])
Product.create!(name: 'M6Si', brand_id: 10, sub_category_ids: [3])

# Wharfedale
Product.create!(name: 'Denton 85th', brand_id: 15, sub_category_ids: [10])
Product.create!(name: 'Dovedale', brand_id: 15, sub_category_ids: [11])

# Willsenton
Product.create!(name: 'R8', brand_id: 16, sub_category_ids: [3])
Product.create!(name: 'R800i', brand_id: 16, sub_category_ids: [3])
