# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?

Category.create!(name: 'Amplifiers')
Category.create!(name: 'CD Players')
Category.create!(name: 'DACs')
Category.create!(name: 'Headphones')
Category.create!(name: 'Loudspeakers')
Category.create!(name: 'Turntables')
Category.create!(name: 'Cartridges')
Category.create!(name: 'Tonearms')

SubCategory.create!(name: 'Pre-Amplifier', category_id: 1)
SubCategory.create!(name: 'Phono Pre-Amplifier', category_id: 1)
SubCategory.create!(name: 'Integrated Amplifier', category_id: 1)
SubCategory.create!(name: 'Power Amplifier', category_id: 1)
SubCategory.create!(name: 'Headphone Amplifier', category_id: 1)
SubCategory.create!(name: 'In-Ear', category_id: 4)
SubCategory.create!(name: 'On-Ear', category_id: 4)
SubCategory.create!(name: 'Over-Ear', category_id: 4)
SubCategory.create!(name: 'Noise Cancelling', category_id: 4)
SubCategory.create!(name: 'Bookshelf', category_id: 5)
SubCategory.create!(name: 'Floorstanding', category_id: 5)
SubCategory.create!(name: 'Subwoofers', category_id: 5)

Tag.create!(name: 'Solid State')
Tag.create!(name: 'Tube')

Manufacturer.create!(name: 'Accuphase')
Manufacturer.create!(name: 'Acoustic Research')
Manufacturer.create!(name: 'Acoustic Signature')
Manufacturer.create!(name: 'Acoustic Solid')
Manufacturer.create!(name: 'Adcom')
Manufacturer.create!(name: 'AKG')
Manufacturer.create!(name: 'AMG (Analog Manufaktur Germany)')
Manufacturer.create!(name: 'Anthem')
Manufacturer.create!(name: 'Arcam')
Manufacturer.create!(name: 'Artisan Fidelity')
Manufacturer.create!(name: 'Atoll Electronique')
Manufacturer.create!(name: 'Audeze')
Manufacturer.create!(name: 'Audio Research')
Manufacturer.create!(name: 'Audio-Technica')
Manufacturer.create!(name: 'AVID HiFi')
Manufacturer.create!(name: 'Ayre Acoustics')
Manufacturer.create!(name: 'Bang & Olufsen')
Manufacturer.create!(name: 'Basis Audio')
Manufacturer.create!(name: 'Benchmark Media Systems')
Manufacturer.create!(name: 'Bergmann Audio')
Manufacturer.create!(name: 'Beyerdynamic')
Manufacturer.create!(name: 'Bluesound')
Manufacturer.create!(name: 'Bose')
Manufacturer.create!(name: 'Brinkmann Audio')
Manufacturer.create!(name: 'Bryston')
Manufacturer.create!(name: 'Cambridge Audio')
Manufacturer.create!(name: 'Campfire Audio')
Manufacturer.create!(name: 'Cary Audio')
Manufacturer.create!(name: 'Cayin')
Manufacturer.create!(name: 'Classe')
Manufacturer.create!(name: 'Clearaudio')
Manufacturer.create!(name: 'Cleer Audio')
Manufacturer.create!(name: 'Creek Audio')
Manufacturer.create!(name: 'Cyrus Audio')
Manufacturer.create!(name: 'Dali')
Manufacturer.create!(name: 'Decware')
Manufacturer.create!(name: 'Denon')
Manufacturer.create!(name: 'Devialet')
Manufacturer.create!(name: 'DeVORE Fidelity')
Manufacturer.create!(name: 'Dr. Feickert Analogue')
Manufacturer.create!(name: 'Dual')
Manufacturer.create!(name: 'EAT (European Audio Team)')
Manufacturer.create!(name: 'ELAC')
Manufacturer.create!(name: 'Emotiva')
Manufacturer.create!(name: 'EMT (Elektro-Mess-Technik)')
Manufacturer.create!(name: 'Esoteric')
Manufacturer.create!(name: 'Exposure Electronics')
Manufacturer.create!(name: 'Feliks Audio')
Manufacturer.create!(name: 'Fern & Roby')
Manufacturer.create!(name: 'Fezz Audio')
Manufacturer.create!(name: 'Focal')
Manufacturer.create!(name: 'Funk Firm')
Manufacturer.create!(name: 'Garrard')
Manufacturer.create!(name: 'GoldenEar Technology')
Manufacturer.create!(name: 'Grado Labs')
Manufacturer.create!(name: 'Hanss Acoustics')
Manufacturer.create!(name: 'Hegel')
Manufacturer.create!(name: 'Hifiman')
Manufacturer.create!(name: 'J. Sikora')
Manufacturer.create!(name: 'JBL')
Manufacturer.create!(name: 'JL Audio')
Manufacturer.create!(name: 'Klipsch')
Manufacturer.create!(name: 'Krell Industries')
Manufacturer.create!(name: 'Kronos Audio')
Manufacturer.create!(name: 'Kuzma')
Manufacturer.create!(name: 'Lenco')
Manufacturer.create!(name: 'Line Magnetic')
Manufacturer.create!(name: 'Linn Products')
Manufacturer.create!(name: 'Luxman')
Manufacturer.create!(name: 'Marantz')
Manufacturer.create!(name: 'Mark Levinson')
Manufacturer.create!(name: 'MartinLogan')
Manufacturer.create!(name: 'Master & Dynamic')
Manufacturer.create!(name: 'McIntosh')
Manufacturer.create!(name: 'Meridian Audio')
Manufacturer.create!(name: 'Meze Audio')
Manufacturer.create!(name: 'Michell Engineering')
Manufacturer.create!(name: 'Moon by Simaudio')
Manufacturer.create!(name: 'Music Hall')
Manufacturer.create!(name: 'Musical Fidelity')
Manufacturer.create!(name: 'Mytek Digital')
Manufacturer.create!(name: 'NAD Electronics')
Manufacturer.create!(name: 'Naim Audio')
Manufacturer.create!(name: 'Nottingham Analogue')
Manufacturer.create!(name: 'Onkyo')
Manufacturer.create!(name: 'Oppo Digital')
Manufacturer.create!(name: 'Oracle Audio')
Manufacturer.create!(name: 'Palmer Audio')
Manufacturer.create!(name: 'Parasound')
Manufacturer.create!(name: 'Pass Labs')
Manufacturer.create!(name: 'Peachtree Audio')
Manufacturer.create!(name: 'Peachtree Audio')
Manufacturer.create!(name: 'Philips')
Manufacturer.create!(name: 'Pioneer')
Manufacturer.create!(name: 'PMC Speakers')
Manufacturer.create!(name: 'PrimaLuna')
Manufacturer.create!(name: 'Primare')
Manufacturer.create!(name: 'Pro-Ject')
Manufacturer.create!(name: 'PS Audio')
Manufacturer.create!(name: 'Quad')
Manufacturer.create!(name: 'Rega Research')
Manufacturer.create!(name: 'Rogue Audio')
Manufacturer.create!(name: 'Roksan')
Manufacturer.create!(name: 'Rotel')
Manufacturer.create!(name: 'SAT (Swedish Analog Technologies)')
Manufacturer.create!(name: 'Sennheiser')
Manufacturer.create!(name: 'Shanling')
Manufacturer.create!(name: 'Shure')
Manufacturer.create!(name: 'Simaudio')
Manufacturer.create!(name: 'SME (SME Limited)')
Manufacturer.create!(name: 'Sonos')
Manufacturer.create!(name: 'Sonus Faber')
Manufacturer.create!(name: 'Sony')
Manufacturer.create!(name: 'Spiral Groove')
Manufacturer.create!(name: 'SPL')
Manufacturer.create!(name: 'Stax')
Manufacturer.create!(name: 'TEAC')
Manufacturer.create!(name: 'Technics')
Manufacturer.create!(name: 'Thorens')
Manufacturer.create!(name: 'Transrotor')
Manufacturer.create!(name: 'Triangle Art')
Manufacturer.create!(name: 'Ultrasone')
Manufacturer.create!(name: 'Unison Research')
Manufacturer.create!(name: 'V-MODA')
Manufacturer.create!(name: 'Vertere Acoustics')
Manufacturer.create!(name: 'Vincent Audio')
Manufacturer.create!(name: 'VPI Industries')
Manufacturer.create!(name: 'Well Tempered Lab')
Manufacturer.create!(name: 'Wharfedale')
Manufacturer.create!(name: 'Willsenton Audio')
Manufacturer.create!(name: 'Wilson Audio')
Manufacturer.create!(name: 'Yamaha')
Manufacturer.create!(name: 'ZMF Headphones')
Manufacturer.create!(name: 'Zu Audio')

# Clearaudio
Product.create!(name: 'Concept', manufacturer_id: 31, category_id: 6)
Product.create!(name: 'Concept Active', manufacturer_id: 31, category_id: 6)
Product.create!(name: 'Emotion SE', manufacturer_id: 31, category_id: 6)
Product.create!(name: 'Performance DC', manufacturer_id: 31, category_id: 6)
Product.create!(name: 'Ovation', manufacturer_id: 31, category_id: 6)
Product.create!(name: 'Reference Jubilee', manufacturer_id: 31, category_id: 6)
Product.create!(name: 'Innovation', manufacturer_id: 31, category_id: 6)
Product.create!(name: 'Innovation Basic', manufacturer_id: 31, category_id: 6)
Product.create!(name: 'Innovation Compact', manufacturer_id: 31, category_id: 6)
Product.create!(name: 'Master Innovation', manufacturer_id: 31, category_id: 6)
Product.create!(name: 'Statement', manufacturer_id: 31, category_id: 6)
Product.create!(name: 'Nano Phono v2', manufacturer_id: 31, category_id: 1, sub_category_id: 2)
Product.create!(name: 'Verify', manufacturer_id: 31, category_id: 8)
Product.create!(name: 'Clarify', manufacturer_id: 31, category_id: 8)
Product.create!(name: 'Satisfy Kardan', manufacturer_id: 31, category_id: 8)
Product.create!(name: 'Profiler', manufacturer_id: 31, category_id: 8)
Product.create!(name: 'Unify', manufacturer_id: 31, category_id: 8)
Product.create!(name: 'Tracer', manufacturer_id: 31, category_id: 8)
Product.create!(name: 'Magnify', manufacturer_id: 31, category_id: 8)
Product.create!(name: 'Universal', manufacturer_id: 31, category_id: 8)
Product.create!(name: 'TT5', manufacturer_id: 31, category_id: 8)
Product.create!(name: 'TT3', manufacturer_id: 31, category_id: 8)
Product.create!(name: 'TT2', manufacturer_id: 31, category_id: 8)
Product.create!(name: 'MM Concept v2', manufacturer_id: 31, category_id: 7)
Product.create!(name: 'Performer v2', manufacturer_id: 31, category_id: 7)
Product.create!(name: 'Artist v2', manufacturer_id: 31, category_id: 7)
Product.create!(name: 'MM Jubilee', manufacturer_id: 31, category_id: 7)
Product.create!(name: 'Virtuso v2', manufacturer_id: 31, category_id: 7)
Product.create!(name: 'Maestro v2', manufacturer_id: 31, category_id: 7)
Product.create!(name: 'Charisma v2', manufacturer_id: 31, category_id: 7)
Product.create!(name: 'Concept MC', manufacturer_id: 31, category_id: 7)
Product.create!(name: 'Essence MC', manufacturer_id: 31, category_id: 7)
Product.create!(name: 'Talisman v2 Gold', manufacturer_id: 31, category_id: 7)
Product.create!(name: 'Concerto v2', manufacturer_id: 31, category_id: 7)
Product.create!(name: 'Stradivari v2', manufacturer_id: 31, category_id: 7)
Product.create!(name: 'Jubilee v2', manufacturer_id: 31, category_id: 7)
Product.create!(name: 'Da Vinci v2', manufacturer_id: 31, category_id: 7)
Product.create!(name: 'Titanium v2', manufacturer_id: 31, category_id: 7)

# Denon
Product.create!(name: 'AH-MM400', manufacturer_id: 36, category_id: 4, sub_category_id: 8, discontinued: true)
Product.create!(name: 'AH-D5200', manufacturer_id: 36, category_id: 4, sub_category_id: 8)
Product.create!(name: 'AH-D7200', manufacturer_id: 36, category_id: 4, sub_category_id: 8)
Product.create!(name: 'AH-D9200', manufacturer_id: 36, category_id: 4, sub_category_id: 8)

# Feliks Audio
Product.create!(name: 'Envy', manufacturer_id: 46, category_id: 1, sub_category_id: 5)
Product.create!(name: 'Euforia Anniversary', manufacturer_id: 46, category_id: 1, sub_category_id: 5)
Product.create!(name: 'Euforia Evo', manufacturer_id: 46, category_id: 1, sub_category_id: 5)
Product.create!(name: 'Elise', manufacturer_id: 46, category_id: 1, sub_category_id: 5)
Product.create!(name: 'Echo 2', manufacturer_id: 46, category_id: 1, sub_category_id: 5)
Product.create!(name: 'Arioso 300B', manufacturer_id: 46, category_id: 1, sub_category_id: 3)

# Musical Fidelity
Product.create!(name: 'M3Si', manufacturer_id: 78, category_id: 1, sub_category_id: 3)
Product.create!(name: 'M5Si', manufacturer_id: 78, category_id: 1, sub_category_id: 3)
Product.create!(name: 'M6Si', manufacturer_id: 78, category_id: 1, sub_category_id: 3)
