# frozen_string_literal: true

# Classifies the existing `full_name` values into `abbreviation` / `legal_name`.
#
# It never *modifies* a string. Every rule decides which column an existing value belongs
# in; nothing is trimmed, generated or shortened. The legal-suffix pattern recognises a
# value, it does not strip one.
#
# The two cheap rules run as SQL because they leave `name` alone. The promotion rule goes
# through the model, because it changes `name` and everything downstream has to follow:
# friendly_id regenerates the brand slug, and Brand's after_update re-slugs the brand's
# products (their slugs embed the brand name). Both of those are ordinary application
# behaviour -- this migration only has to route through the model to get them.
#
# Only brands that actually have a `full_name` are loaded, so the model round-trip stays
# cheap however large the catalogue gets.
#
# Whatever no rule can classify keeps its `full_name` and is listed at the end, to be sorted
# out by hand in ActiveAdmin (which still shows and filters the column) before `full_name` is
# dropped in a later release.
class BackfillBrandNamesFromFullName < ActiveRecord::Migration[8.1]
  # Recognises a value that is a registered company name. Anchored to the end and to a word
  # boundary so "Audio Note (UK) Ltd" matches but "Agena Audio" does not match on the "ag".
  LEGAL_SUFFIX = '\\y(gmbh|ag|inc|ltd|limited|llc|plc|corp|corporation|company|co|' \
                 'kk|oy|ab|aps|a/s|as|sarl|srl|nv|bv|sa|spa|pty|pte)\\.?\\s*$'

  def up
    Brand.reset_column_information

    say_with_time 'Clearing full_name values that only repeat name' do
      execute("UPDATE brands SET full_name = NULL WHERE full_name IS NOT NULL AND full_name = name")
    end

    say_with_time 'Moving registered company names into legal_name' do
      execute(<<~SQL.squish)
        UPDATE brands
        SET legal_name = full_name, full_name = NULL
        WHERE full_name IS NOT NULL AND full_name ~* '#{LEGAL_SUFFIX}'
      SQL
    end

    promoted, leftovers = promote_remaining_full_names
    report(promoted, leftovers)
  end

  # Not reversible: the promotion in `up` moves `previous_name` into `abbreviation`, and
  # Brand#clear_abbreviation_when_contained_in_name (R4) then nulls it right back out for
  # every brand where the old name was a substring of the new one -- the common case. Once
  # that happens the pre-migration `name` exists nowhere in the row, so there is nothing a
  # `down` could reconstruct it from. Recovery is the database reset this migration's header
  # comment already documents, not a partial rollback.
  def down
    raise ActiveRecord::IrreversibleMigration
  end

  private

  # `name` holds a short form and `full_name` holds what the brand actually calls itself, in
  # one of two shapes:
  #
  #   "Fezz"  / "Fezz Audio"      -- every word of name appears in full_name
  #   "B&O"   / "Bang & Olufsen"  -- name is the initials of full_name
  #
  # Both swap the same way. Which of them keeps its old name as an `abbreviation` is not
  # decided here: Brand#clear_abbreviation_when_contained_in_name drops "Fezz" (searching it
  # already finds "Fezz Audio" through `name`) and keeps "B&O" (it does not). One code path,
  # and the redundancy rule stays defined in exactly one place.
  #
  # Anything else -- "Technics" / "Panasonic", which is an ownership relationship rather than
  # a naming one -- is left alone for a human.
  def promote_remaining_full_names
    promoted = []
    leftovers = []

    Brand.where.not(full_name: nil).find_each do |brand|
      previous_name = brand.name
      target = brand.full_name

      unless contained_in?(previous_name, target) || initials_of?(previous_name, target)
        leftovers << [brand.id, previous_name, target]
        next
      end

      begin
        rename_brand(brand, target, previous_name)
        promoted << [previous_name, brand.reload.name]
      rescue StandardError => e
        leftovers << [brand.id, previous_name, "#{target} (#{e.message})"]
      end
    end

    [promoted, leftovers]
  end

  # The brand's own slug is regenerated by friendly_id on save. Its products' slugs are not
  # -- nothing on Product notices a brand rename -- so Brand's after_update calls
  # Product.resync_slugs_for. That is ordinary application behaviour, not migration-only, so
  # this migration deliberately has no copy of it.
  def rename_brand(brand, target, previous_name)
    preserve_slug_in_history(brand)

    brand.name = target
    brand.abbreviation = previous_name
    brand.full_name = nil
    brand.save!
  end

  # Brands slugged before :history was in use may have no row for their current slug, and
  # without one the old URL 404s the moment the slug changes. Products get the equivalent
  # treatment from Product#preserve_current_slug_in_history.
  def preserve_slug_in_history(brand)
    return if brand.slug.blank?
    return if FriendlyId::Slug.exists?(sluggable_type: 'Brand', sluggable_id: brand.id, slug: brand.slug)

    FriendlyId::Slug.create!(
      sluggable_type: 'Brand', sluggable_id: brand.id, slug: brand.slug, created_at: Time.current
    )
  end

  def contained_in?(short, long)
    tokens(long).to_set.superset?(tokens(short).to_set)
  end

  def initials_of?(short, long)
    initials = tokens(long).filter_map { |token| token[0] }.join
    initials.present? && tokens(short).join == initials
  end

  # The same normalisation RelevanceOrdering and pg_search use, so "would searching the name
  # already find this?" is answered here the way search would answer it.
  def tokens(value)
    value.to_s.downcase.gsub(Regexp.new(RelevanceOrdering::STRIP_PATTERN), '').split
  end

  def report(promoted, leftovers)
    if promoted.any?
      say "Promoted #{promoted.size} brand name(s); old slugs now 301 to the new ones:"
      promoted.each { |from, to| say("  #{from}  ->  #{to}", true) }
    end

    return say('No unclassified full_name values left.') if leftovers.empty?

    say("#{leftovers.size} brand(s) still have a full_name that needs a human decision:")
    leftovers.each { |id, name, full_name| say("  ##{id}  #{name}  ->  #{full_name}", true) }
    say('Sort these out in ActiveAdmin before full_name is dropped.')
  end
end
